# -*- coding: utf-8 -*-
import time
from io import BytesIO

import OpenOPC
import paho.mqtt.publish as publish
import requests
from PIL import Image, ImageGrab
from flask import Flask, request, jsonify
from flask import send_file
from flask.ext.cors import CORS

app = Flask(__name__)  # 实例化app对象
CORS(app)


# 冷冻机组控制
@app.route('/ldj/write/', methods=['GET'])  # 路由
def opc_write():
    opc = OpenOPC.client()  # 创建客户端
    opc.connect(u'PCAuto.OPCServer', 'localhost')  # 读取opc
    pointName = request.values["pointName"]  # 获取坐取按钮信息
    pointValue = request.values["pointValue"]
    opc.write((str(pointName), float(pointValue)))  # 写入opc值
    time.sleep(1)
    lista = ['ZLJ3_ManAuto.PV', "ZLJ3_ManOn.PV", "ZLJ3_Run.PV", "FJ3_ManAuto.PV", "FJ3_ManOn.PV", "FJ3_Run.PV",
             "LDB3_ManAuto.PV", "LDB3_ManOn.PV", "LDB3_Run.PV", "LQB3_ManAuto.PV", "LQB3_ManOn.PV",
             "LQB3_Run.PV"]  # 控制集
    # ('ZLJ3_ManAuto.PV',1.0)手动模式
    # ('ZLJ3_ManOn.PV', 1.0)启动冷冻机
    # opc.write( ('ZLJ3_ManOn.PV', 0.0) )关闭冷冻机命令1
    # opc.write( ('ZLJ3_Run.PV', 0.0) )关闭冷冻机命令2

    # opc['LQB3_ManAuto.PV'] = 1.0 冷却泵3手动
    # ('LQB3_ManOn.PV', 1.0)启动冷却泵3
    # opc.write( ('LQB3_ManOn.PV', 0.0) )关闭冷却泵3命令1
    # opc.write( ('LQB3_Run.PV', 0.0) )关闭冷却泵3命令2

    # opc['LDB3_ManAuto.PV'] = 1.0 冷冻泵3手动
    # ('LDB3_ManOn.PV', 1.0)启动冷冻泵3
    # opc.write( ('LDB3_ManOn.PV', 0.0) )关闭冷冻泵3命令1
    # opc.write( ('LDB3_Run.PV', 0.0) )关闭冷冻泵3命令2

    # checkOpc = opc.read(str(pointName))  # 校验得到的返回结果，判断命令是否下发成功
    # if float(checkOpc[1]) == pointValue:
    return jsonify({"data": "命令下发成功！"})
    # else:
    #    return jsonify({"data": "命令下发失败！"})


# 冷冻机组控制结果查询
@app.route('/ldj/status/', methods=['GET'])  # 路由
def opc_status():
    opc = OpenOPC.client()  # 创建客户端
    opc.connect(u'PCAuto.OPCServer', 'localhost')  # 读取opcserver
    lista = ['ZLJ3_ManAuto.PV', "ZLJ3_ManOn.PV", "ZLJ3_Run.PV", "FJ3_ManAuto.PV", "FJ3_ManOn.PV", "FJ3_Run.PV",
             "LDB3_ManAuto.PV", "LDB3_ManOn.PV", "LDB3_Run.PV", "LQB3_ManAuto.PV", "LQB3_ManOn.PV", "LQB3_Run.PV"]
    listStatus = []
    opcList = opc.read(lista)  # 读取整个流程参数 0停止和手动  1启动和自动
    for line in opcList:
        collection = {}
        collection[line[0]] = line[1]
        listStatus.append(collection)
    return jsonify(listStatus)  # f返回状态结果集


# 冷冻机组控实时图片（1280*800）
@app.route('/ldj/picture/', methods=['GET'])  # 路由
def opc_picture():
    imgScreen = ImageGrab.grab()
    imgScreen.save('windowsOPC.png')
    time.sleep(1)
    img = Image.open('windowsOPC.png')
    byte_io = BytesIO()
    img.save(byte_io, 'PNG')
    byte_io.seek(0)
    return send_file(byte_io, mimetype='image/png')


# 风机盘管组控制
@app.route('/pg/write/', methods=['GET'])  # 路由
def pg_write():
    pointX = request.args.get('pointX', 1)  # 坐标点
    pointY = request.args.get('pointY', 1)
    print(1111)
    result = requests.get("http://10.65.244.162:5000/imageBack", params={'x': int(pointX), 'y': int(pointY)})  # 下发命令
    return jsonify(result.status_code)  # 返回200及成功


# 风机盘管组控制状态回调(图片1024*600)
@app.route('/pg/status/', methods=['GET'])
def pgImage():
    html = requests.get("http://10.65.244.162:5000/image")  # 获取上层接口屏幕图片
    with open('picture.png', 'wb') as file:  # 保存获取的图片
        file.write(html.content)
    img = Image.open("picture.png")
    byte_io = BytesIO()
    img.save(byte_io, 'PNG')
    byte_io.seek(0)
    return send_file(byte_io, mimetype='image/png')  # 转发图片


# 新风系统控制
@app.route('/xf/write/', methods=['GET'])
def xfWrite():
    point = request.values["point"]  # 坐标点
    HOST = "47.95.252.59"
    PORT = 61613
    client_id = time.strftime('%Y%m%d%H%M%S', time.localtime(time.time()))
    publish.single("subTop", payload=point, qos=1, hostname=HOST, port=PORT, client_id=client_id,
                   auth={'username': "admin", 'password': "password"}, transport="tcp")
    return jsonify({'data': "success!"})


# 冷冻机read1
@app.route('/ldj/read1/', methods=['GET'])
def ldjRead1():
    opc = OpenOPC.client()  # 创建客户端
    opc.connect(u'PCAuto.OPCServer', 'localhost')  # 读取opcserver
    lista = ['FJ1_Alarm.PV', 'FJ1_FreSP.PV', 'FJ1_ManAuto.PV', 'FJ1_ManOn.PV', 'FJ1_Run.PV', 'FJ1_RunTime.PV',
             'FJ2_Alarm.PV', 'FJ2_FreSP.PV', 'FJ2_ManAuto.PV', 'FJ2_ManOn.PV', 'FJ2_Run.PV', 'FJ2_RunTime.PV',
             'FJ3_Alarm.PV', 'FJ3_FreSP.PV', 'FJ3_ManAuto.PV', 'FJ3_ManOn.PV', 'FJ3_Run.PV', 'FJ3_RunTime.PV',
             'FJ4_Alarm.PV', 'FJ4_FreSP.PV', 'FJ4_ManAuto.PV', 'FJ4_ManOn.PV', 'FJ4_Run.PV', 'FJ4_RunTime.PV',
             'FJ5_Alarm.PV', 'FJ5_FreSP.PV', 'FJ5_ManAuto.PV', 'FJ5_ManOn.PV', 'FJ5_Run.PV', 'FJ5_RunTime.PV',
             'HL1HS_Press.PV', 'HL1HS_Tem.PV', 'HL2HS_Press.PV', 'HL2HS_Tem.PV', 'HL3HS_Press.PV', 'HL3HS_Tem.PV',
             'LDB1_Alarm.PV', 'LDB1_Clear.PV', 'LDB1_FreSP.PV', 'LDB1_ManAuto.PV', 'LDB1_ManOn.PV', 'LDB1_NeedRep.PV',
             'LDB1_Repair.PV', 'LDB1_Run.PV', 'LDB2_Alarm.PV', 'LDB2_Clear.PV', 'LDB2_FreSP.PV', 'LDB2_ManAuto.PV',
             'LDB2_ManOn.PV', 'LDB2_NeedRep.PV', 'LDB2_Repair.PV', 'LDB2_Run.PV', 'LDB3_Alarm.PV', 'LDB3_Clear.PV',
             'LDB3_FreSP.PV', 'LDB3_ManAuto.PV', 'LDB3_ManOn.PV', 'LDB3_NeedRep.PV', 'LDB3_Repair.PV', 'LDB3_Run.PV',
             'LDB4_Alarm.PV', 'LDB4_Clear.PV', 'LDB4_FreSP.PV', 'LDB4_ManAuto.PV', 'LDB4_ManOn.PV', 'LDB4_NeedRep.PV',
             'LDB4_Repair.PV', 'LDB4_Run.PV', 'LDF1_FBClose.PV', 'LDF1_FBOpen.PV', 'LDF2_FBClose.PV', 'LDF2_FBOpen.PV',
             'LDF3_FBClose.PV', 'LDF3_FBOpen.PV', 'LDGS1_Tem.PV', 'LDHS1_Tem.PV', 'LQB1_Alarm.PV', 'LQB1_Clear.PV',
             'LQB1_FreSP.PV', 'LQB1_ManAuto.PV', 'LQB1_ManOn.PV', 'LQB1_NeedRep.PV', 'LQB1_Repair.PV', 'LQB1_Run.PV',
             'LQB2_Alarm.PV', 'LQB2_Clear.PV', 'LQB2_FreSP.PV', 'LQB2_ManAuto.PV', 'LQB2_ManOn.PV', 'LQB2_NeedRep.PV',
             'LQB2_Repair.PV', 'LQB2_Run.PV', 'LQB3_Alarm.PV', 'LQB3_Clear.PV', 'LQB3_FreSP.PV', 'LQB3_ManAuto.PV',
             'LQB3_ManOn.PV', 'LQB3_NeedRep.PV', 'LQB3_Repair.PV', 'LQB3_Run.PV', 'LQB4_Alarm.PV', 'LQB4_Clear.PV',
             'LQB4_FreSP.PV', 'LQB4_ManAuto.PV', 'LQB4_ManOn.PV', 'LQB4_NeedRep.PV', 'LQB4_Repair.PV', 'LQB4_Run.PV',
             'LQGS1_Tem.PV', 'LQHS1_Tem.PV', 'ZLJ1_A.PV', 'ZLJ1_Alarm.PV', 'ZLJ1_KW.PV', 'ZLJ1_KWh.PV',
             'ZLJ1_ManAuto.PV', 'ZLJ1_ManOn.PV', 'ZLJ1_Run.PV', 'ZLJ1_RunTime.PV', 'ZLJ2_A.PV', 'ZLJ2_Alarm.PV',
             'ZLJ2_KW.PV', 'ZLJ2_KWh.PV', 'ZLJ2_ManAuto.PV', 'ZLJ2_ManOn.PV', 'ZLJ2_Run.PV', 'ZLJ2_RunTime.PV',
             'ZLJ3_A.PV', 'ZLJ3_Alarm.PV', 'ZLJ3_KW.PV', 'ZLJ3_KWh.PV', 'ZLJ3_ManAuto.PV', 'ZLJ3_ManOn.PV',
             'ZLJ3_Run.PV', 'ZLJ3_RunTime.PV']
    listStatus = []
    opcList = opc.read(lista)  # 读取整个流程参数 0停止和手动  1启动和自动
    for line in opcList:
        collection = {}
        collection[line[0]] = line[1]
        listStatus.append(collection)
    return jsonify(listStatus)  # f返回状态结果集


# 冷冻机read2
@app.route('/ldj/read2/', methods=['GET'])
def ldjRead1():
    opc = OpenOPC.client()  # 创建客户端
    opc.connect(u'PCAuto.OPCServer', 'localhost')  # 读取opcserver
    lista = ['ZLJ1_DAT4.PV', 'ZLJ1_DAT5.PV', 'ZLJ1_DAT6.PV', 'ZLJ1_DAT7.PV', 'ZLJ1_DAT8.PV', 'ZLJ1_DAT9.PV',
             'ZLJ1_KW.PV', 'ZLJ1_KWh.PV', 'ZLJ1_ManAuto.PV', 'ZLJ1_ManOn.PV', 'ZLJ1_Mode.PV', 'ZLJ1_NeedRep.PV',
             'ZLJ1_Repair.PV', 'ZLJ1_RepTime.PV', 'ZLJ1_Run.PV', 'ZLJ1_RunTime.PV', 'ZLJ1_TemSet.PV', 'ZLJ2_A.PV',
             'ZLJ2_Alarm.PV', 'ZLJ2_ASet.PV', 'ZLJ2_ChuShi.PV', 'ZLJ2_Clear.PV', 'ZLJ2_DAT1.PV', 'ZLJ2_DAT10.PV',
             'ZLJ2_DAT11.PV', 'ZLJ2_DAT12.PV', 'ZLJ2_DAT13.PV', 'ZLJ2_DAT14.PV', 'ZLJ2_DAT15.PV', 'ZLJ2_DAT16.PV',
             'ZLJ2_DAT17.PV', 'ZLJ2_DAT18.PV', 'ZLJ2_DAT19.PV', 'ZLJ2_DAT2.PV', 'ZLJ2_DAT20.PV', 'ZLJ2_DAT21.PV',
             'ZLJ2_DAT22.PV', 'ZLJ2_DAT23.PV', 'ZLJ2_DAT24.PV', 'ZLJ2_DAT25.PV', 'ZLJ2_DAT3.PV', 'ZLJ2_DAT4.PV',
             'ZLJ2_DAT5.PV', 'ZLJ2_DAT6.PV', 'ZLJ2_DAT7.PV', 'ZLJ2_DAT8.PV', 'ZLJ2_DAT9.PV', 'ZLJ2_KW.PV',
             'ZLJ2_KWh.PV', 'ZLJ2_ManAuto.PV', 'ZLJ2_ManOn.PV', 'ZLJ2_Mode.PV', 'ZLJ2_NeedRep.PV', 'ZLJ2_Repair.PV',
             'ZLJ2_RepTime.PV', 'ZLJ2_Run.PV', 'ZLJ2_RunTime.PV', 'ZLJ2_TemSet.PV', 'ZLJ3_A.PV', 'ZLJ3_Alarm.PV',
             'ZLJ3_ASet.PV', 'ZLJ3_ChuShi.PV', 'ZLJ3_Clear.PV', 'ZLJ3_DAT1.PV', 'ZLJ3_DAT10.PV', 'ZLJ3_DAT11.PV',
             'ZLJ3_DAT12.PV', 'ZLJ3_DAT13.PV', 'ZLJ3_DAT14.PV', 'ZLJ3_DAT15.PV', 'ZLJ3_DAT16.PV', 'ZLJ3_DAT17.PV',
             'ZLJ3_DAT18.PV', 'ZLJ3_DAT19.PV', 'ZLJ3_DAT2.PV', 'ZLJ3_DAT20.PV', 'ZLJ3_DAT21.PV', 'ZLJ3_DAT22.PV',
             'ZLJ3_DAT23.PV', 'ZLJ3_DAT24.PV', 'ZLJ3_DAT25.PV', 'ZLJ3_DAT3.PV', 'ZLJ3_DAT4.PV', 'ZLJ3_DAT5.PV',
             'ZLJ3_DAT6.PV', 'ZLJ3_DAT7.PV', 'ZLJ3_DAT8.PV', 'ZLJ3_DAT9.PV', 'ZLJ3_KW.PV', 'ZLJ3_KWh.PV',
             'ZLJ3_ManAuto.PV', 'ZLJ3_ManOn.PV', 'ZLJ3_Mode.PV', 'ZLJ3_NeedRep.PV', 'ZLJ3_Repair.PV', 'ZLJ3_RepTime.PV',
             'ZLJ3_Run.PV', 'ZLJ3_RunTime.PV', 'ZLJ3_TemSet.PV', 'ZLJ4_A.PV', 'ZLJ4_Alarm.PV', 'ZLJ4_ChuShi.PV',
             'ZLJ4_Clear.PV', 'ZLJ4_KW.PV', 'ZLJ4_KWh.PV', 'ZLJ4_ManAuto.PV', 'ZLJ4_ManOn.PV', 'ZLJ4_Mode.PV',
             'ZLJ4_NeedRep.PV', 'ZLJ4_Repair.PV', 'ZLJ4_RepTime.PV', 'ZLJ4_Run.PV', 'ZLJ4_RunTime.PV', 'ZLJ5_A.PV',
             'ZLJ5_Alarm.PV', 'ZLJ5_ChuShi.PV', 'ZLJ5_Clear.PV', 'ZLJ5_KW.PV', 'ZLJ5_KWh.PV', 'ZLJ5_ManAuto.PV',
             'ZLJ5_ManOn.PV', 'ZLJ5_Mode.PV', 'ZLJ5_NeedRep.PV', 'ZLJ5_Repair.PV', 'ZLJ5_RepTime.PV', 'ZLJ5_Run.PV',
             'ZLJ5_RunTime.PV', 'ZLJ6_A.PV', 'ZLJ6_Alarm.PV', 'ZLJ6_ChuShi.PV', 'ZLJ6_Clear.PV', 'ZLJ6_KW.PV',
             'ZLJ6_KWh.PV', 'ZLJ6_ManAuto.PV', 'ZLJ6_ManOn.PV', 'ZLJ6_Mode.PV', 'ZLJ6_NeedRep.PV', 'ZLJ6_Repair.PV',
             'ZLJ6_RepTime.PV', 'ZLJ6_Run.PV', 'ZLJ6_RunTime.PV', 'ZQ_LJLL.PV', 'ZQ_LJRL.PV', 'ZQ_MD.PV', 'ZQ_PL.PV',
             'ZQ_RH.PV', 'ZQ_SSLL.PV', 'ZQ_SSRL.PV', 'ZQ_WD.PV', 'ZQ_YC.PV', 'ZQ_YL.PV', 'RSB1_KWh.PV',
             'RSB1_ManAuto.PV', 'RSB1_ManOn.PV', 'RSB1_Mode.PV', 'RSB1_NeedRep.PV', 'RSB1_Repair.PV', 'RSB1_RepTime.PV',
             'RSB1_Run.PV', 'RSB1_RunTime.PV', 'RSB2_A.PV', 'RSB2_Alarm.PV', 'RSB2_Clear.PV', 'RSB2_Fre_FB.PV',
             'RSB2_FreSP.PV', 'RSB2_KW.PV', 'RSB2_KWh.PV', 'RSB2_ManAuto.PV', 'RSB2_ManOn.PV', 'RSB2_Mode.PV',
             'RSB2_NeedRep.PV', 'RSB2_Repair.PV', 'RSB2_RepTime.PV', 'RSB2_Run.PV', 'RSB2_RunTime.PV', 'RSB2_Sec.PV',
             'RSB3_A.PV', 'RSB3_Alarm.PV', 'RSB3_Clear.PV', 'RSB3_Fre_FB.PV', 'RSB3_FreSP.PV', 'RSB3_KW.PV',
             'RSB3_KWh.PV', 'RSB3_ManAuto.PV', 'RSB3_ManOn.PV', 'RSB3_Mode.PV', 'RSB3_NeedRep.PV', 'RSB3_Repair.PV',
             'RSB3_RepTime.PV', 'RSB3_Run.PV', 'RSB3_RunTime.PV', 'RSB3_Sec.PV', 'RSB4_A.PV', 'RSB4_Alarm.PV',
             'RSB4_Clear.PV', 'RSB4_Fre_FB.PV', 'RSB4_FreSP.PV', 'RSB4_KW.PV', 'RSB4_KWh.PV', 'RSB4_ManAuto.PV',
             'RSB4_ManOn.PV', 'RSB4_Mode.PV', 'RSB4_NeedRep.PV', 'RSB4_Repair.PV', 'RSB4_RepTime.PV', 'RSB4_Run.PV',
             'RSB4_RunTime.PV', 'RSB5_A.PV', 'RSB5_Alarm.PV', 'RSB5_Clear.PV', 'RSB5_Fre_FB.PV', 'RSB5_FreSP.PV',
             'RSB5_KW.PV', 'RSB5_KWh.PV', 'RSB5_ManAuto.PV', 'RSB5_ManOn.PV', 'RSB5_Mode.PV', 'RSB5_NeedRep.PV',
             'RSB5_Repair.PV', 'RSB5_RepTime.PV', 'RSB5_Run.PV', 'RSB5_RunTime.PV', 'RSB6_A.PV', 'RSB6_Alarm.PV',
             'RSB6_Clear.PV', 'RSB6_Fre_FB.PV', 'RSB6_FreSP.PV', 'RSB6_KW.PV', 'RSB6_KWh.PV', 'RSB6_ManAuto.PV',
             'RSB6_ManOn.PV', 'RSB6_Mode.PV', 'RSB6_NeedRep.PV', 'RSB6_Repair.PV', 'RSB6_RepTime.PV', 'RSB6_Run.PV',
             'RSB6_RunTime.PV', 'RSF1_Close.PV', 'RSF1_FBClose.PV', 'RSF1_FBOpen.PV', 'RSF1_ManAuto.PV', 'RSF1_Open.PV',
             'RSF2_Close.PV', 'RSF2_FBClose.PV', 'RSF2_FBOpen.PV', 'RSF2_ManAuto.PV', 'RSF2_Open.PV', 'RSF3_Close.PV',
             'RSF3_FBClose.PV', 'RSF3_FBOpen.PV', 'RSF3_ManAuto.PV', 'RSF3_Open.PV', 'RSF4_Close.PV', 'RSF4_FBClose.PV',
             'RSF4_FBOpen.PV', 'RSF4_ManAuto.PV', 'RSF4_Open.PV', 'RSF5_Close.PV', 'RSF5_FBClose.PV', 'RSF5_FBOpen.PV',
             'RSF5_ManAuto.PV', 'RSF5_Open.PV', 'RSF6_Close.PV', 'RSF6_FBClose.PV', 'RSF6_FBOpen.PV', 'RSF6_ManAuto.PV',
             'RSF6_Open.PV', 'RSGS_PH.PV', 'RSGS_PL.PV', 'RSGS_TH.PV', 'RSGS1_Tem.PV', 'RSGS2_Tem.PV', 'RSGST_SP.PV',
             'RSHS_PH.PV', 'RSHS_PL.PV', 'RSHS_TH.PV', 'RSHS1_Tem.PV', 'RSHS2_Tem.PV', 'RST.PV', 'SQ_Tem.PV',
             'SQT_SP1.PV', 'SQT_SP10.PV', 'SQT_SP2.PV', 'SQT_SP3.PV', 'SQT_SP4.PV', 'SQT_SP5.PV', 'SQT_SP6.PV',
             'SQT_SP7.PV', 'SQT_SP8.PV', 'SQT_SP9.PV', 'SSLL.PV', 'SSRL.PV', 'Start_Time2.PV', 'Step1.PV', 'Step2.PV',
             'Step3.PV', 'Step4.PV', 'Step5.PV', 'Step6.PV', 'SUB_Cur2.PV', 'Sub_Pan1.PV', 'Sub_Pan2.PV', 'SubDelay.PV',
             'Sumer_End.PV', 'Sumer_Start.PV', 'TJF_ManAuto1.PV', 'TJF_ManAuto2.PV', 'TJF_ManAuto3.PV',
             'TJF_ManAuto4.PV', 'TJF1_FB.PV', 'TJF2_FB.PV', 'TJF3_FB.PV', 'TJF4_FB.PV', 'TRQ_N.PV', 'TTJ_DB.PV',
             'TTJ_I.PV', 'TTJ_OutSP1.PV', 'TTJ_OutSP2.PV', 'TTJ_OutSP3.PV', 'TTJ_OutSP4.PV', 'TTJ_P.PV', 'WeekEn1.PV',
             'WeekEn2.PV', 'WeekEn3.PV', 'WeekEn4.PV', 'WeekEn5.PV', 'WeekEn6.PV', 'WeekEn7.PV', 'XT_Alarm1.PV',
             'XT_Alarm10.PV', 'XT_Alarm11.PV', 'XT_Alarm12.PV', 'XT_Alarm13.PV', 'XT_Alarm14.PV', 'XT_Alarm15.PV',
             'XT_Alarm16.PV', 'XT_Alarm17.PV', 'XT_Alarm18.PV', 'XT_Alarm19.PV', 'XT_Alarm2.PV', 'XT_Alarm20.PV',
             'XT_Alarm21.PV', 'XT_Alarm22.PV', 'XT_Alarm23.PV', 'XT_Alarm24.PV', 'XT_Alarm25.PV', 'XT_Alarm26.PV',
             'XT_Alarm3.PV', 'XT_Alarm4.PV', 'XT_Alarm5.PV', 'XT_Alarm6.PV', 'XT_Alarm7.PV', 'XT_Alarm8.PV',
             'XT_Alarm9.PV', 'XT_H.PV', 'XT_H1.PV', 'XT_L.PV', 'XT_L1.PV', 'XT_M.PV', 'XT_M1.PV', 'XTZ_KW.PV',
             'XTZ_KWh.PV', 'XTZR_KW.PV', 'XTZR_KWh.PV', 'YC_SP1.PV', 'YC_SP10.PV', 'YC_SP2.PV', 'YC_SP3.PV',
             'YC_SP4.PV', 'YC_SP5.PV', 'YC_SP6.PV', 'YC_SP7.PV', 'YC_SP8.PV', 'YC_SP9.PV', 'ZLJ_DNB1.PV',
             'ZLJ_ENAuto.PV', 'ZLJ_ERROR1.PV', 'ZLJ_ERROR2.PV', 'ZLJ_ERROR3.PV', 'ZLJ_KW.PV', 'ZLJ_KWh.PV',
             'ZLJ_TemSP.PV', 'ZLJ_TemSP1.PV', 'ZLJ_TemSP2.PV', 'ZLJ_TemSP3.PV', 'ZLJ_TemSP4.PV', 'ZLJ_TemSPEN1.PV',
             'ZLJ_TemSPEN2.PV', 'ZLJ_TemSPEN3.PV', 'ZLJ_TemSPEN4.PV', 'ZLJ1_A.PV', 'ZLJ1_Alarm.PV', 'ZLJ1_ASet.PV',
             'ZLJ1_ChuShi.PV', 'ZLJ1_Clear.PV', 'ZLJ1_DAT1.PV', 'ZLJ1_DAT10.PV', 'ZLJ1_DAT11.PV', 'ZLJ1_DAT12.PV',
             'ZLJ1_DAT13.PV', 'ZLJ1_DAT14.PV', 'ZLJ1_DAT15.PV', 'ZLJ1_DAT16.PV', 'ZLJ1_DAT17.PV', 'ZLJ1_DAT18.PV',
             'ZLJ1_DAT19.PV', 'ZLJ1_DAT2.PV', 'ZLJ1_DAT20.PV', 'ZLJ1_DAT21.PV', 'ZLJ1_DAT22.PV', 'ZLJ1_DAT23.PV',
             'ZLJ1_DAT24.PV', 'ZLJ1_DAT25.PV', 'ZLJ1_DAT3.PV', 'MOnMinute2.PV', 'MOnMinute3.PV', 'MOnMinute4.PV',
             'MOnMinute5.PV', 'MOnMinute6.PV', 'MOnMinute7.PV', 'MOUT_Hum.PV', 'MOUT_Tem.PV', 'MOutTem_EN.PV',
             'MParA1.PV', 'MParA10.PV', 'MParA2.PV', 'MParA3.PV', 'MParA4.PV', 'MParA5.PV', 'MParA6.PV', 'MParA7.PV',
             'MParA8.PV', 'MParA9.PV', 'MParB1.PV', 'MParB10.PV', 'MParB2.PV', 'MParB3.PV', 'MParB4.PV', 'MParB5.PV',
             'MParB6.PV', 'MParB7.PV', 'MParB8.PV', 'MParB9.PV', 'MParC1.PV', 'MParC10.PV', 'MParC2.PV', 'MParC3.PV',
             'MParC4.PV', 'MParC5.PV', 'MParC6.PV', 'MParC7.PV', 'MParC8.PV', 'MParC9.PV', 'MParD1.PV', 'MParD10.PV',
             'MParD2.PV', 'MParD3.PV', 'MParD4.PV', 'MParD5.PV', 'MParD6.PV', 'MParD7.PV', 'MParD8.PV', 'MParD9.PV',
             'MParE1.PV', 'MParE10.PV', 'MParE2.PV', 'MParE3.PV', 'MParE4.PV', 'MParE5.PV', 'MParE6.PV', 'MParE7.PV',
             'MParE8.PV', 'MParE9.PV', 'MPC_Day.PV', 'MPC_Hour.PV', 'MPC_Minute.PV', 'MPC_Month.PV', 'MPC_Year.PV',
             'MPHF_DB.PV', 'MPHF_FB1.PV', 'MPHF_FB2.PV', 'MPHF_FB3.PV', 'MPHF_FB4.PV', 'MPHF_HighSP.PV', 'MPHF_I.PV',
             'MPHF_LowSP.PV', 'MPHF_ManAuto1.PV', 'MPHF_ManAuto2.PV', 'MPHF_ManAuto3.PV', 'MPHF_ManAuto4.PV',
             'MPHF_OutSP1.PV', 'MPHF_OutSP2.PV', 'MPHF_OutSP3.PV', 'MPHF_OutSP4.PV', 'MPHF_P.PV', 'MRKWD.PV',
             'MRLLJ.PV', 'MRSB_DB.PV', 'MRSB_DNB1.PV', 'MRSB_HighSP1.PV', 'MRSB_I.PV', 'MRSB_KW.PV', 'MRSB_KWh.PV',
             'MRSB_P.PV', 'MRSB1_A.PV', 'MRSB1_Alarm.PV', 'MRSB1_Clear.PV', 'MRSB1_Fre_FB.PV', 'MRSB1_FreSP.PV',
             'MRSB1_KW.PV', 'MRSB1_KWh.PV', 'MRSB1_ManAuto.PV', 'MRSB1_ManOn.PV', 'MRSB1_Mode.PV', 'MRSB1_NeedRep.PV',
             'MRSB1_Repair.PV', 'MRSB1_RepTime.PV', 'MRSB1_Run.PV', 'MRSB1_RunTime.PV', 'MRSB2_A.PV', 'MRSB2_Alarm.PV',
             'MRSB2_Clear.PV', 'MRSB2_Fre_FB.PV', 'MRSB2_FreSP.PV', 'MRSB2_KW.PV', 'MRSB2_KWh.PV', 'MRSB2_ManAuto.PV',
             'MRSB2_ManOn.PV', 'MRSB2_Mode.PV', 'MRSB2_NeedRep.PV', 'MRSB2_Repair.PV', 'MRSB2_RepTime.PV',
             'MRSB2_Run.PV', 'MRSB2_RunTime.PV', 'MRSB3_A.PV', 'MRSB3_Alarm.PV', 'MRSB3_Clear.PV', 'MRSB3_Fre_FB.PV',
             'MRSB3_FreSP.PV', 'MRSB3_KW.PV', 'MRSB3_KWh.PV', 'MRSB3_ManAuto.PV', 'MRSB3_ManOn.PV', 'MRSB3_Mode.PV',
             'MRSB3_NeedRep.PV', 'MRSB3_Repair.PV', 'MRSB3_RepTime.PV', 'MRSB3_Run.PV', 'MRSB3_RunTime.PV',
             'MRSB4_A.PV', 'MRSB4_Alarm.PV', 'MRSB4_Clear.PV', 'MRSB4_Fre_FB.PV', 'MRSB4_FreSP.PV', 'MRSB4_KW.PV',
             'MRSB4_KWh.PV', 'MRSB4_ManAuto.PV', 'MRSB4_ManOn.PV', 'MRSB4_Mode.PV', 'MRSB4_NeedRep.PV',
             'MRSB4_Repair.PV', 'MRSB4_RepTime.PV', 'MRSB4_Run.PV', 'MRSB4_RunTime.PV', 'MRSB5_A.PV', 'MRSB5_Alarm.PV',
             'MRSB5_Clear.PV', 'MRSB5_Fre_FB.PV', 'MRSB5_FreSP.PV', 'MRSB5_KW.PV', 'MRSB5_KWh.PV', 'MRSB5_ManAuto.PV',
             'MRSB5_ManOn.PV', 'MRSB5_Mode.PV', 'MRSB5_NeedRep.PV', 'MRSB5_Repair.PV', 'MRSB5_RepTime.PV',
             'MRSB5_Run.PV', 'MRSB5_RunTime.PV', 'MRSB6_A.PV', 'MRSB6_Alarm.PV', 'MRSB6_Clear.PV', 'MRSB6_Fre_FB.PV',
             'MRSB6_FreSP.PV', 'MRSB6_KW.PV', 'MRSB6_KWh.PV', 'MRSB6_ManAuto.PV', 'MRSB6_ManOn.PV', 'MRSB6_Mode.PV',
             'MRSB6_NeedRep.PV', 'MRSB6_Repair.PV', 'MRSB6_RepTime.PV', 'MRSB6_Run.PV', 'MRSB6_RunTime.PV',
             'MRSF1_Close.PV', 'MRSF1_FBClose.PV', 'MRSF1_FBOpen.PV', 'MRSF1_ManAuto.PV', 'MRSF1_Open.PV',
             'MRSF2_Close.PV', 'MRSF2_FBClose.PV', 'MRSF2_FBOpen.PV', 'MRSF2_ManAuto.PV', 'MRSF2_Open.PV',
             'MRSF3_Close.PV', 'MRSF3_FBClose.PV', 'MRSF3_FBOpen.PV', 'MRSF3_ManAuto.PV', 'MRSF3_Open.PV',
             'MRSF4_Close.PV', 'MRSF4_FBClose.PV', 'MRSF4_FBOpen.PV', 'MRSF4_ManAuto.PV', 'MRSF4_Open.PV',
             'MRSF5_Close.PV', 'MRSF5_FBClose.PV', 'MRSF5_FBOpen.PV', 'MRSF5_ManAuto.PV', 'MRSF5_Open.PV',
             'MRSF6_Close.PV', 'MRSF6_FBClose.PV', 'MRSF6_FBOpen.PV', 'MRSF6_ManAuto.PV', 'MRSF6_Open.PV',
             'MRSGS1_Tem.PV', 'MRSGS2_Tem.PV', 'MRSGST_SP.PV', 'MRSHS1_Tem.PV', 'MRSHS2_Tem.PV', 'MSQ_Tem.PV',
             'MSQT_SP1.PV', 'MSQT_SP10.PV', 'MSQT_SP2.PV', 'MSQT_SP3.PV', 'MSQT_SP4.PV', 'MSQT_SP5.PV', 'MSQT_SP6.PV',
             'MSQT_SP7.PV', 'MSQT_SP8.PV', 'MSQT_SP9.PV', 'MSSLL.PV', 'MSSRL.PV', 'MStart_Time2.PV', 'MStep1.PV',
             'MStep2.PV', 'MStep3.PV', 'MStep4.PV', 'MStep5.PV', 'MStep6.PV', 'MSUB_Cur2.PV', 'MSub_Pan1.PV',
             'MSub_Pan2.PV', 'MSubDelay.PV', 'MSumer_End.PV', 'MSumer_Start.PV', 'MTJF_ManAuto1.PV', 'MTJF_ManAuto2.PV',
             'MTJF_ManAuto3.PV', 'MTJF_ManAuto4.PV', 'MTJF1_FB.PV', 'MTJF2_FB.PV', 'MTJF3_FB.PV', 'MTJF4_FB.PV',
             'MTRQ_N.PV', 'MTTJ_DB.PV', 'MTTJ_I.PV', 'MTTJ_OutSP1.PV', 'MTTJ_OutSP2.PV', 'MTTJ_OutSP3.PV',
             'MTTJ_OutSP4.PV', 'MTTJ_P.PV', 'MWeekEn1.PV', 'MWeekEn2.PV', 'MWeekEn3.PV', 'MWeekEn4.PV', 'MWeekEn5.PV',
             'MWeekEn6.PV', '1HL_LowX4.PV', '1HL_LowX6.PV', '1ADD_Cur1.PV', '1FJSQ_P_SPD.PV', '1HL_LowX3.PV',
             '1ADD_T.PV', '1HL_LowX1.PV', '1HL_LowX2.PV', '1HL_LowX8.PV', '1HL_LowX10.PV', '1HL_LowX9.PV',
             '1FJSQ_P_SPX.PV', '1HL_LowX7.PV', '1HL_LowX5.PV', '1HL_Tem_SPD1.PV', '1HL_Tem_SPD10.PV', '1HL_Tem_SPD2.PV',
             '1HL_Tem_SPD3.PV', '1HL_Tem_SPD4.PV', '1HL_Tem_SPD5.PV', '1HL_Tem_SPD6.PV', '1HL_Tem_SPD7.PV',
             '1HL_Tem_SPD8.PV', '1HL_Tem_SPD9.PV', '1HL_Tem_SPX1.PV', '1HL_Tem_SPX10.PV', '1HL_Tem_SPX2.PV',
             '1HL_Tem_SPX3.PV', '1HL_Tem_SPX4.PV', '1HL_Tem_SPX5.PV', '1HL_Tem_SPX6.PV', '1HL_Tem_SPX7.PV',
             '1HL_Tem_SPX8.PV', '1HL_Tem_SPX9.PV', '1LDB_Hz_Low.PV', '1LDGS_P_SP1.PV', '1LDGS_P_SP2.PV',
             '1LDGS_P_SP3.PV', '1LDGS_P_SP4.PV', '1LDGS_P_SP5.PV', '1LDGS_P_SP6.PV', '1LQB_Hz_Low.PV', '1RSB_Hz_Low.PV',
             '1RSGS_P_SP1.PV', '1RSGS_P_SP2.PV', '1RSGS_P_SP3.PV', '1RSGS_Tem_SP.PV', '1SUB_Cur1.PV', '1SUB_T.PV',
             '1ZLJ_MAX.PV', '1ZLJ_MIN.PV', '1ZQF_Low.PV', '2ADD_Cur1.PV', '2ADD_T.PV', '2FJSQ_P_SPD.PV',
             '2FJSQ_P_SPX.PV', '2HL_LowX1.PV', '2HL_LowX10.PV', '2HL_LowX2.PV', '2HL_LowX3.PV', '2HL_LowX4.PV',
             '2HL_LowX5.PV', '2HL_LowX6.PV', '2HL_LowX7.PV', 'FJ5_RunTime.PV', 'FJ6_A.PV', 'FJ6_Alarm.PV',
             'FJ6_Clear.PV', 'FJ6_Fre_FB.PV', 'FJ6_FreSP.PV', 'FJ6_KW.PV', 'FJ6_KWh.PV', 'FJ6_ManAuto.PV',
             'FJ6_ManOn.PV', 'FJ6_Mode.PV', 'FJ6_NeedRep.PV', 'FJ6_Repair.PV', 'FJ6_RepTime.PV', 'FJ6_Run.PV',
             'FJ6_RunTime.PV', 'FJ7_A.PV', 'FJ7_Alarm.PV', 'FJ7_Clear.PV', 'FJ7_Fre_FB.PV', 'FJ7_FreSP.PV', 'FJ7_KW.PV',
             'FJ7_KWh.PV', 'FJ7_ManAuto.PV', 'FJ7_ManOn.PV', 'FJ7_Mode.PV', 'FJ7_NeedRep.PV', 'FJ7_Repair.PV',
             'FJ7_RepTime.PV', 'FJ7_Run.PV', 'FJ7_RunTime.PV', 'FJ8_A.PV', 'FJ8_Alarm.PV', 'FJ8_Clear.PV',
             'FJ8_Fre_FB.PV', 'FJ8_FreSP.PV', 'FJ8_KW.PV', 'FJ8_KWh.PV', 'FJ8_ManAuto.PV', 'FJ8_ManOn.PV',
             'FJ8_Mode.PV', 'FJ8_NeedRep.PV', 'FJ8_Repair.PV', 'FJ8_RepTime.PV', 'FJ8_Run.PV', 'FJ8_RunTime.PV',
             'FJ9_Alarm.PV', 'FJ9_Clear.PV', 'FJ9_Fre_FB.PV', 'FJ9_FreSP.PV', 'FJ9_ManAuto.PV', 'FJ9_ManOn.PV',
             'FJ9_Mode.PV', 'FJ9_NeedRep.PV', 'FJ9_Repair.PV', 'FJ9_RepTime.PV', 'FJ9_Run.PV', 'FJ9_RunTime.PV',
             'FM_CloseTime1.PV', 'FM_CloseTime2.PV', 'FM_CloseTime3.PV', 'FM_CloseTime4.PV', 'FM_CloseTime5.PV',
             'FM_CloseTime6.PV', 'FM_OpenTime1.PV', 'FM_OpenTime2.PV', 'FM_OpenTime3.PV', 'FM_OpenTime4.PV',
             'FM_OpenTime5.PV', 'FM_OpenTime6.PV', 'FSQ_Press1.PV', 'FSQ_Press2.PV', 'G1.PV', 'G2.PV', 'G3.PV', 'G4.PV',
             'G5.PV', 'G6.PV', 'G7.PV', 'G8.PV', 'GJ_Time1.PV', 'GJ_Time2.PV', 'GJ_Time3.PV', 'GJ_Time4.PV',
             'GJ_Time5.PV', 'GJ_Time6.PV', 'GJ_Time7.PV', 'GL_DNB1.PV', 'GL_KW.PV', 'GL_KWh.PV', 'GL1_A.PV',
             'GL1_ADATA1.PV', 'GL1_ADATA2.PV', 'GL1_ADATA3.PV', 'GL1_ADATA4.PV', 'GL1_ADATA5.PV', 'GL1_Alarm.PV',
             'GL1_ChuShi.PV', 'GL1_Clear.PV', 'GL1_DATA1.PV', 'GL1_DATA10.PV', 'GL1_DATA11.PV', 'GL1_DATA12.PV',
             'GL1_DATA2.PV', 'GL1_DATA3.PV', 'GL1_DATA4.PV', 'GL1_DATA5.PV', 'GL1_DATA6.PV', 'GL1_DATA7.PV',
             'GL1_DATA8.PV', 'GL1_DATA9.PV', 'GL1_KW.PV', 'GL1_KWh.PV', 'GL1_ManAuto.PV', 'GL1_ManOn.PV', 'GL1_Mode.PV',
             'GL1_NeedRep.PV', 'GL1_Repair.PV', 'GL1_RepTime.PV', 'GL1_Run.PV', 'GL1_RunTime.PV', 'GL2_A.PV',
             'GL2_ADATA1.PV', 'GL2_ADATA2.PV', 'GL2_ADATA3.PV', 'GL2_ADATA4.PV', 'GL2_ADATA5.PV', 'GL2_Alarm.PV',
             'GL2_ChuShi.PV', 'GL2_Clear.PV', 'GL2_DATA1.PV', 'GL2_DATA10.PV', 'GL2_DATA11.PV', 'GL2_DATA12.PV',
             'GL2_DATA2.PV', 'GL2_DATA3.PV', 'GL2_DATA4.PV', 'GL2_DATA5.PV', 'GL2_DATA6.PV', 'GL2_DATA7.PV',
             'GL2_DATA8.PV', 'GL2_DATA9.PV', 'GL2_KW.PV', 'GL2_KWh.PV', 'GL2_ManAuto.PV', 'GL2_ManOn.PV', 'GL2_Mode.PV',
             'GL2_NeedRep.PV', 'GL2_Repair.PV', 'GL2_RepTime.PV', 'GL2_Run.PV', 'GL2_RunTime.PV', 'GL3_A.PV',
             'GL3_Alarm.PV', 'GL3_ChuShi.PV', 'GL3_Clear.PV', 'GL3_KW.PV', 'GL3_KWh.PV', 'GL3_ManAuto.PV',
             'GL3_ManOn.PV', 'GL3_Mode.PV', 'GL3_NeedRep.PV', 'GL3_Repair.PV', 'GL3_RepTime.PV', 'GL3_Run.PV',
             'GL3_RunTime.PV', 'GL4_A.PV', 'GL4_Alarm.PV', 'GL4_ChuShi.PV', 'GL4_Clear.PV', 'GL4_KW.PV', 'GL4_KWh.PV',
             'GL4_ManAuto.PV', 'GL4_ManOn.PV', 'GL4_Mode.PV', 'GL4_NeedRep.PV', 'GL4_Repair.PV', 'GL4_RepTime.PV',
             'GL4_Run.PV', 'GL4_RunTime.PV', 'GongKuang_EN.PV', 'GongPing.PV', 'GPWDD.PV', 'GPWDX.PV', 'H1.PV', 'H2.PV',
             'H3.PV', 'H4.PV', 'H5.PV', 'H6.PV', 'H7.PV', 'H8.PV', 'HL1_BuChang.PV', 'HL1_BuChangSP.PV', 'HL1_Flow.PV',
             'HL1_WenBian.PV', 'HL1_YuQi_Tem.PV', 'HL1_ZhouQi.PV', 'HL10_BuChang.PV', 'HL10_BuChangSP.PV',
             'HL10_Flow.PV', 'HL10_WenBian.PV', 'HL10_YuQi_Tem.PV', 'HL10_ZhouQi.PV', 'HL10HS_Press.PV',
             'HL10HS_Tem.PV', 'HL1HS_Press.PV', 'HL1HS_Tem.PV', 'HL2_BuChang.PV', 'HL2_BuChangSP.PV', 'HL2_Flow.PV',
             'HL2_WenBian.PV', 'HL2_YuQi_Tem.PV', 'HL2_ZhouQi.PV', 'HL2HS_Press.PV', 'HL2HS_Tem.PV', 'HL3_BuChang.PV',
             'HL3_BuChangSP.PV', 'HL3_Flow.PV', 'HL3_WenBian.PV', 'HL3_YuQi_Tem.PV', 'HL3_ZhouQi.PV', 'HL3HS_Press.PV',
             'HL3HS_Tem.PV', 'HL4_BuChang.PV', 'HL4_BuChangSP.PV', 'HL4_Flow.PV', 'HL4_WenBian.PV', 'HL4_YuQi_Tem.PV',
             'HL4_ZhouQi.PV', 'HL4HS_Press.PV', 'HL4HS_Tem.PV', 'HL5_BuChang.PV', 'HL5_BuChangSP.PV', 'HL5_Flow.PV',
             'HL5_WenBian.PV', 'HL5_YuQi_Tem.PV', 'HL5_ZhouQi.PV', 'HL5HS_Press.PV', 'HL5HS_Tem.PV', 'HL6_BuChang.PV',
             'HL6_BuChangSP.PV', 'HL6_Flow.PV', 'HL6_WenBian.PV', 'HL6_YuQi_Tem.PV', 'HL6_ZhouQi.PV', 'HL6HS_Press.PV',
             'HL6HS_Tem.PV', 'HL7_BuChang.PV', 'HL7_BuChangSP.PV', 'HL7_Flow.PV', 'HL7_WenBian.PV', 'HL7_YuQi_Tem.PV',
             'HL7_ZhouQi.PV', 'HL7HS_Press.PV', 'HL7HS_Tem.PV', 'HL8_BuChang.PV', 'HL8_BuChangSP.PV', 'HL8_Flow.PV',
             'HL8_WenBian.PV', 'HL8_YuQi_Tem.PV', 'HL8_ZhouQi.PV', 'HL8HS_Press.PV', 'LDB7_Alarm.PV', 'LDB7_Clear.PV',
             'LDB7_Fre_FB.PV', 'LDB7_FreSP.PV', 'LDB7_KW.PV', 'LDB7_KWh.PV', 'LDB7_ManAuto.PV', 'LDB7_ManOn.PV',
             'LDB7_Mode.PV', 'LDB7_NeedRep.PV', 'LDB7_Repair.PV', 'LDB7_RepTime.PV', 'LDB7_Run.PV', 'LDB7_RunTime.PV',
             'LDB8_A.PV', 'LDB8_Alarm.PV', 'LDB8_Clear.PV', 'LDB8_Fre_FB.PV', 'LDB8_FreSP.PV', 'LDB8_KW.PV',
             'LDB8_KWh.PV', 'LDB8_ManAuto.PV', 'LDB8_ManOn.PV', 'LDB8_Mode.PV', 'LDB8_NeedRep.PV', 'LDB8_Repair.PV',
             'LDB8_RepTime.PV', 'LDB8_Run.PV', 'LDB8_RunTime.PV', 'LDF_Stop1.PV', 'LDF_Stop2.PV', 'LDF_Stop3.PV',
             'LDF_Stop4.PV', 'LDF_Stop5.PV', 'LDF_Stop6.PV', 'LDF1_Close.PV', 'LDF1_FBClose.PV', 'LDF1_FBOpen.PV',
             'LDF1_ManAuto.PV', 'LDF1_Open.PV', 'LDF2_Close.PV', 'LDF2_FBClose.PV', 'LDF2_FBOpen.PV', 'LDF2_ManAuto.PV',
             'LDF2_Open.PV', 'LDF3_Close.PV', 'LDF3_FBClose.PV', 'LDF3_FBOpen.PV', 'LDF3_ManAuto.PV', 'LDF3_Open.PV',
             'LDF4_Close.PV', 'LDF4_FBClose.PV', 'LDF4_FBOpen.PV', 'LDF4_ManAuto.PV', 'LDF4_Open.PV', 'LDF5_Close.PV',
             'LDF5_FBClose.PV', 'LDF5_FBOpen.PV', 'LDF5_ManAuto.PV', 'LDF5_Open.PV', 'LDF6_Close.PV', 'LDF6_FBClose.PV',
             'LDF6_FBOpen.PV', 'LDF6_ManAuto.PV', 'LDF6_Open.PV', 'LDGS1_Tem.PV', 'LDGS2_Tem.PV', 'LDHS1_Tem.PV',
             'LDHS2_Tem.PV', 'LDZG1_Flow.PV', 'LDZG2_Flow.PV', 'LengReLiang.PV', 'LLLJ.PV', 'LOAD.PV', 'LQB_DB.PV',
             'LQB_DNB1.PV', 'LQB_ERROR1.PV', 'HL8HS_Tem.PV', 'HL9_BuChang.PV', 'HL9_BuChangSP.PV', 'HL9_Flow.PV',
             'HL9_WenBian.PV', 'HL9_YuQi_Tem.PV', 'HL9_ZhouQi.PV', 'HL9HS_Press.PV', 'HL9HS_Tem.PV', 'HLF_DB.PV',
             'HLF_EN1.PV', 'HLF_EN10.PV', 'HLF_EN2.PV', 'HLF_EN3.PV', 'HLF_EN4.PV', 'HLF_EN5.PV', 'HLF_EN6.PV',
             'HLF_EN7.PV', 'HLF_EN8.PV', 'HLF_EN9.PV', 'HLF_I.PV', 'HLF_P.PV', 'HLF1_FB.PV', 'HLF1_ManAuto.PV',
             'HLF1_OutSP.PV', 'HLF10_FB.PV', 'HLF10_ManAuto.PV', 'HLF10_OutSP.PV', 'HLF2_FB.PV', 'HLF2_ManAuto.PV',
             'HLF2_OutSP.PV', 'HLF3_FB.PV', 'HLF3_ManAuto.PV', 'HLF3_OutSP.PV', 'HLF4_FB.PV', 'HLF4_ManAuto.PV',
             'HLF4_OutSP.PV', 'HLF5_FB.PV', 'HLF5_ManAuto.PV', 'HLF5_OutSP.PV', 'HLF6_FB.PV', 'HLF6_ManAuto.PV',
             'HLF6_OutSP.PV', 'HLF7_FB.PV', 'HLF7_ManAuto.PV', 'HLF7_OutSP.PV', 'HLF8_FB.PV', 'HLF8_ManAuto.PV',
             'HLF8_OutSP.PV', 'HLF9_FB.PV', 'HLF9_ManAuto.PV', 'HLF9_OutSP.PV', 'HLKD_H1.PV', 'HLKD_H10.PV',
             'HLKD_H2.PV', 'HLKD_H3.PV', 'HLKD_H4.PV', 'HLKD_H5.PV', 'HLKD_H6.PV', 'HLKD_H7.PV', 'HLKD_H8.PV',
             'HLKD_H9.PV', 'HLKD_L1.PV', 'HLKD_L10.PV', 'HLKD_L2.PV', 'HLKD_L3.PV', 'HLKD_L4.PV', 'HLKD_L5.PV',
             'HLKD_L6.PV', 'HLKD_L7.PV', 'HLKD_L8.PV', 'HLKD_L9.PV', 'HLKD_M1.PV', 'HLKD_M10.PV', 'HLKD_M2.PV',
             'HLKD_M3.PV', 'HLKD_M4.PV', 'HLKD_M5.PV', 'HLKD_M6.PV', 'HLKD_M7.PV', 'HLKD_M8.PV', 'HLKD_M9.PV',
             'Hz_H.PV', 'Hz_L.PV', 'Hz_M.PV', 'I1.PV', 'I2.PV', 'I3.PV', 'I4.PV', 'I5.PV', 'I6.PV', 'I7.PV', 'I8.PV',
             'J1.PV', 'J2.PV', 'J3.PV', 'J4.PV', 'J5.PV', 'J6.PV', 'J7.PV', 'J8.PV', 'JiJieMode.PV', 'JSQ_Press1.PV',
             'JSQ_Press2.PV', 'KJ_Time1.PV', 'KJ_Time2.PV', 'KJ_Time3.PV', 'KJ_Time4.PV', 'KJ_Time5.PV', 'KJ_Time6.PV',
             'KJ_Time7.PV', 'KW_DNB1.PV', 'KW_DNB2.PV', 'KW_DNB3.PV', 'KW_DNB4.PV', 'KW_DNB5.PV', 'KW_DNB6.PV',
             'KW_DNB7.PV', 'KWH_DNB1.PV', 'KWH_DNB2.PV', 'KWH_DNB3.PV', 'KWH_DNB4.PV', 'KWH_DNB5.PV', 'KWH_DNB6.PV',
             'KWH_DNB7.PV', 'L1A_DNB1.PV', 'L1A_DNB2.PV', 'L1A_DNB3.PV', 'L1A_DNB4.PV', 'L1A_DNB5.PV', 'L1A_DNB6.PV',
             'L1A_DNB7.PV', 'L2A_DNB1.PV', 'L2A_DNB2.PV', 'L2A_DNB3.PV', 'L2A_DNB4.PV', 'L2A_DNB5.PV', 'L2A_DNB6.PV',
             'L2A_DNB7.PV', 'L3A_DNB1.PV', 'L3A_DNB2.PV', 'L3A_DNB3.PV', 'L3A_DNB4.PV', 'L3A_DNB5.PV', 'L3A_DNB6.PV',
             'L3A_DNB7.PV', 'LDB_DB.PV', 'LDB_DNB1.PV', 'LDB_ERROR1.PV', 'LDB_ERROR2.PV', 'LDB_ERROR3.PV',
             'LDB_ERROR4.PV', 'LDB_HighSP1.PV', 'LDB_I.PV', 'LDB_KW.PV', 'LDB_KWh.PV', 'LDB_OffTime1.PV',
             'LDB_OffTime2.PV', 'LDB_OffTime3.PV', 'LDB_OffTime4.PV', 'LDB_OffTime5.PV', 'LDB_OffTime6.PV',
             'LDB_OnTime1.PV', 'LDB_OnTime2.PV', 'LDB_OnTime3.PV', 'LDB_OnTime4.PV', 'LDB_OnTime5.PV', 'LDB_OnTime6.PV',
             'LDB_P.PV', 'LDB_PSet.PV', 'LDB1_A.PV', 'LDB1_Alarm.PV', 'LDB1_Clear.PV', 'LDB1_Fre_FB.PV',
             'LDB1_FreSP.PV', 'LDB1_KW.PV', 'LDB1_KWh.PV', 'LDB1_ManAuto.PV', 'LDB1_ManOn.PV', 'LDB1_Mode.PV',
             'LDB1_NeedRep.PV', 'LDB1_Repair.PV', 'LDB1_RepTime.PV', 'LDB1_Run.PV', 'LDB1_RunTime.PV', 'LDB2_A.PV',
             'LDB2_Alarm.PV', 'LDB2_Clear.PV', 'LDB2_Fre_FB.PV', 'LDB2_FreSP.PV', 'LDB2_KW.PV', 'LDB2_KWh.PV',
             'LDB2_ManAuto.PV', 'LDB2_ManOn.PV', 'LDB2_Mode.PV', 'LDB2_NeedRep.PV', 'LDB2_Repair.PV', 'LDB2_RepTime.PV',
             'LDB2_Run.PV', 'LDB2_RunTime.PV', 'LDB3_A.PV', 'LDB3_Alarm.PV', 'LDB3_Clear.PV', 'LDB3_Fre_FB.PV',
             'LDB3_FreSP.PV', 'LDB3_KW.PV', 'LDB3_KWh.PV', 'LDB3_ManAuto.PV', 'LDB3_ManOn.PV', 'LDB3_Mode.PV',
             'LDB3_NeedRep.PV', 'LDB3_Repair.PV', 'LDB3_RepTime.PV', 'LDB3_Run.PV', 'LDB3_RunTime.PV', 'LDB3_Sec.PV',
             'LDB4_A.PV', 'LDB4_Alarm.PV', 'LDB4_Clear.PV', 'LDB4_Fre_FB.PV', 'LDB4_FreSP.PV', 'LDB4_KW.PV',
             'LDB4_KWh.PV', 'LDB4_ManAuto.PV', 'LDB4_ManOn.PV', 'LDB4_Mode.PV', 'LDB4_NeedRep.PV', 'LDB4_Repair.PV',
             'LDB4_RepTime.PV', 'LDB4_Run.PV', 'LDB4_RunTime.PV', 'LDB4_Sec.PV', 'LDB5_A.PV', 'LDB5_Alarm.PV',
             'LDB5_Clear.PV', 'LDB5_Fre_FB.PV', 'LDB5_FreSP.PV', 'LDB5_KW.PV', 'LDB5_KWh.PV', 'LDB5_ManAuto.PV',
             'LDB5_ManOn.PV', 'LDB5_Mode.PV', 'LDB5_NeedRep.PV', 'LDB5_Repair.PV', 'LDB5_RepTime.PV', 'LDB5_Run.PV',
             'LDB5_RunTime.PV', 'LDB6_A.PV', 'LDB6_Alarm.PV', 'LDB6_Clear.PV', 'LDB6_Fre_FB.PV', 'LDB6_FreSP.PV',
             'LDB6_KW.PV', 'LDB6_KWh.PV', 'LDB6_ManAuto.PV', 'LDB6_ManOn.PV', 'LDB6_Mode.PV', 'LDB6_NeedRep.PV',
             'LDB6_Repair.PV', 'LDB6_RepTime.PV', 'LDB6_Run.PV', 'LDB6_RunTime.PV', 'LDB7_A.PV', 'MDelay1.PV',
             'MDelay2.PV', 'MDelay3.PV', 'MDelay4.PV', 'MDelay5.PV', 'MDelay6.PV', 'MDingShiEn.PV', 'MDNB_Error1.PV',
             'MDNB_Error10.PV', 'MDNB_Error11.PV', 'MDNB_Error12.PV', 'MDNB_Error13.PV', 'MDNB_Error14.PV',
             'MDNB_Error15.PV', 'MDNB_Error16.PV', 'MDNB_Error2.PV', 'MDNB_Error3.PV', 'MDNB_Error4.PV',
             'MDNB_Error5.PV', 'MDNB_Error6.PV', 'MDNB_Error7.PV', 'MDNB_Error8.PV', 'MDNB_Error9.PV', 'MDT_H.PV',
             'MDT_H1.PV', 'MDT_L.PV', 'MDT_L1.PV', 'MDT_M.PV', 'MDT_M1.PV', 'ME1.PV', 'ME2.PV', 'ME3.PV', 'ME4.PV',
             'ME5.PV', 'ME6.PV', 'ME7.PV', 'ME8.PV', 'MECB_DB.PV', 'MECB_DNB1.PV', 'MECB_HighSP1.PV', 'MECB_I.PV',
             'MECB_KW.PV', 'MECB_KWh.PV', 'MECB_P.PV', 'MECB1_A.PV', 'MECB1_Alarm.PV', 'MECB1_Clear.PV',
             'MECB1_Fre_FB.PV', 'MECB1_FreSP.PV', 'MECB1_KW.PV', 'MECB1_KWh.PV', 'MECB1_ManAuto.PV', 'MECB1_ManOn.PV',
             'MECB1_Mode.PV', 'MECB1_NeedRep.PV', 'MECB1_Repair.PV', 'MECB1_RepTime.PV', 'MECB1_Run.PV',
             'MECB1_RunTime.PV', 'MECB2_A.PV', 'MECB2_Alarm.PV', 'MECB2_Clear.PV', 'MECB2_Fre_FB.PV', 'MECB2_FreSP.PV',
             'MECB2_KW.PV', 'MECB2_KWh.PV', 'MECB2_ManAuto.PV', 'MECB2_ManOn.PV', 'MECB2_Mode.PV', 'MECB2_NeedRep.PV',
             'MECB2_Repair.PV', 'MECB2_RepTime.PV', 'MECB2_Run.PV', 'MECB2_RunTime.PV', 'MECB3_A.PV', 'MECB3_Alarm.PV',
             'MECB3_Clear.PV', 'MECB3_Fre_FB.PV', 'MECB3_FreSP.PV', 'MECB3_KW.PV', 'MECB3_KWh.PV', 'MECB3_ManAuto.PV',
             'MECB3_ManOn.PV', 'MECB3_Mode.PV', 'MECB3_NeedRep.PV', 'MECB3_Repair.PV', 'MECB3_RepTime.PV',
             'MECB3_Run.PV', 'MECB3_RunTime.PV', 'MECB4_A.PV', 'MECB4_Alarm.PV', 'MECB4_Clear.PV', 'MECB4_Fre_FB.PV',
             'MECB4_FreSP.PV', 'MECB4_KW.PV', 'MECB4_KWh.PV', 'MECB4_ManAuto.PV', 'MECB4_ManOn.PV', 'MECB4_Mode.PV',
             'MECB4_NeedRep.PV', 'MECB4_Repair.PV', 'MECB4_RepTime.PV', 'MECB4_Run.PV', 'MECB4_RunTime.PV',
             'MECB5_A.PV', 'MECB5_Alarm.PV', 'MECB5_Clear.PV', 'MECB5_Fre_FB.PV', 'MECB5_FreSP.PV', 'MECB5_KW.PV',
             'MECB5_KWh.PV', 'MECB5_ManAuto.PV', 'MECB5_ManOn.PV', 'MECB5_Mode.PV', 'MECB5_NeedRep.PV',
             'MECB5_Repair.PV', 'MECB5_RepTime.PV', 'MECB5_Run.PV', 'MECB5_RunTime.PV', 'MECB6_A.PV', 'MECB6_Alarm.PV',
             'MECB6_Clear.PV', 'MECB6_Fre_FB.PV', 'LQB_ERROR2.PV', 'LQB_ERROR3.PV', 'LQB_ERROR4.PV', 'LQB_HighSP1.PV',
             'LQB_I.PV', 'LQB_KW.PV', 'LQB_KWh.PV', 'LQB_OffTime.PV', 'LQB_P.PV', 'LQB1_A.PV', 'LQB1_Alarm.PV',
             'LQB1_Clear.PV', 'LQB1_Fre_FB.PV', 'LQB1_FreSP.PV', 'LQB1_KW.PV', 'LQB1_KWh.PV', 'LQB1_ManAuto.PV',
             'LQB1_ManOn.PV', 'LQB1_Mode.PV', 'LQB1_NeedRep.PV', 'LQB1_Repair.PV', 'LQB1_RepTime.PV', 'LQB1_Run.PV',
             'LQB1_RunTime.PV', 'LQB2_A.PV', 'LQB2_Alarm.PV', 'LQB2_Clear.PV', 'LQB2_Fre_FB.PV', 'LQB2_FreSP.PV',
             'LQB2_KW.PV', 'LQB2_KWh.PV', 'LQB2_ManAuto.PV', 'LQB2_ManOn.PV', 'LQB2_Mode.PV', 'LQB2_NeedRep.PV',
             'LQB2_Repair.PV', 'LQB2_RepTime.PV', 'LQB2_Run.PV', 'LQB2_RunTime.PV', 'LQB3_A.PV', 'LQB3_Alarm.PV',
             'LQB3_Clear.PV', 'LQB3_Fre_FB.PV', 'LQB3_FreSP.PV', 'LQB3_KW.PV', 'LQB3_KWh.PV', 'LQB3_ManAuto.PV',
             'LQB3_ManOn.PV', 'LQB3_Mode.PV', 'LQB3_NeedRep.PV', 'LQB3_Repair.PV', 'LQB3_RepTime.PV', 'LQB3_Run.PV',
             'LQB3_RunTime.PV', 'LQB4_A.PV', 'LQB4_Alarm.PV', 'LQB4_Clear.PV', 'LQB4_Fre_FB.PV', 'LQB4_FreSP.PV',
             'LQB4_KW.PV', 'LQB4_KWh.PV', 'LQB4_ManAuto.PV', 'LQB4_ManOn.PV', 'LQB4_Mode.PV', 'LQB4_NeedRep.PV',
             'LQB4_Repair.PV', 'LQB4_RepTime.PV', 'LQB4_Run.PV', 'LQB4_RunTime.PV', 'LQB5_A.PV', 'LQB5_Alarm.PV',
             'LQB5_Clear.PV', 'LQB5_Fre_FB.PV', 'LQB5_FreSP.PV', 'LQB5_KW.PV', 'LQB5_KWh.PV', 'LQB5_ManAuto.PV',
             'LQB5_ManOn.PV', 'LQB5_Mode.PV', 'LQB5_NeedRep.PV', 'LQB5_Repair.PV', 'LQB5_RepTime.PV', 'LQB5_Run.PV',
             'LQB5_RunTime.PV', 'LQB6_A.PV', 'LQB6_Alarm.PV', 'LQB6_Clear.PV', 'LQB6_Fre_FB.PV', 'LQB6_FreSP.PV',
             'LQB6_KW.PV', 'LQB6_KWh.PV', 'LQB6_ManAuto.PV', 'LQB6_ManOn.PV', 'LQB6_Mode.PV', 'LQB6_NeedRep.PV',
             'LQB6_Repair.PV', 'LQB6_RepTime.PV', 'LQB6_Run.PV', 'LQB6_RunTime.PV', 'LQB7_A.PV', 'LQB7_Alarm.PV',
             'LQB7_Clear.PV', 'LQB7_Fre_FB.PV', 'LQB7_FreSP.PV', 'LQB7_KW.PV', 'LQB7_KWh.PV', 'LQB7_ManAuto.PV',
             'LQB7_ManOn.PV', 'LQB7_Mode.PV', 'LQB7_NeedRep.PV', 'LQB7_Repair.PV', 'LQB7_RepTime.PV', 'LQB7_Run.PV',
             'LQB7_RunTime.PV', 'LQB8_A.PV', 'LQB8_Alarm.PV', 'LQB8_Clear.PV', 'LQB8_Fre_FB.PV', 'LQB8_FreSP.PV',
             'LQB8_KW.PV', 'LQB8_KWh.PV', 'LQB8_ManAuto.PV', 'LQB8_ManOn.PV', 'LQB8_Mode.PV', 'LQB8_NeedRep.PV',
             'LQB8_Repair.PV', 'LQB8_RepTime.PV', 'LQB8_Run.PV', 'LQB8_RunTime.PV', 'LQF_Stop1.PV', 'LQF_Stop2.PV',
             'LQF_Stop3.PV', 'LQF_Stop4.PV', 'LQF_Stop5.PV', 'LQF_Stop6.PV', 'LQF1_Close.PV', 'LQF1_FBClose.PV',
             'LQF1_FBOpen.PV', 'LQF1_ManAuto.PV', 'LQF1_Open.PV', 'LQF2_Close.PV', 'LQF2_FBClose.PV', 'LQF2_FBOpen.PV',
             'LQF2_ManAuto.PV', 'LQF2_Open.PV', 'LQF3_Close.PV', 'LQF3_FBClose.PV', 'LQF3_FBOpen.PV', 'LQF3_ManAuto.PV',
             'LQF3_Open.PV', 'LQF4_Close.PV', 'LQF4_FBClose.PV', 'LQF4_FBOpen.PV', 'LQF4_ManAuto.PV', 'LQF4_Open.PV',
             'LQF5_Close.PV', 'LQF5_FBClose.PV', 'LQF5_FBOpen.PV', 'LQF5_ManAuto.PV', 'LQF5_Open.PV', 'LQF6_Close.PV',
             'LQF6_FBClose.PV', 'LQF6_FBOpen.PV', 'LQF6_ManAuto.PV', 'LQF6_Open.PV', 'LQGS1_Tem.PV', 'LQGS2_Tem.PV',
             'LQHS1_Tem.PV', 'LQHS2_Tem.PV', 'LQTF1_Close.PV', 'LQTF1_FBClose.PV', 'LQTF1_FBOpen.PV',
             'LQTF1_ManAuto.PV', 'LQTF1_Open.PV', 'LQTF10_Close.PV', 'LQTF10_FBClose.PV', 'LQTF10_FBOpen.PV',
             'LQTF10_ManAuto.PV', 'LQTF10_Open.PV', 'LQTF11_Close.PV', 'LQTF11_FBClose.PV', 'LQTF11_FBOpen.PV',
             'LQTF11_ManAuto.PV', 'LQTF11_Open.PV', 'LQTF12_Close.PV', 'LQTF12_FBClose.PV', 'LQTF12_FBOpen.PV',
             'LQTF12_ManAuto.PV', 'LQTF12_Open.PV', 'LQTF13_Close.PV', 'LQTF13_FBClose.PV', 'LQTF13_FBOpen.PV',
             'LQTF13_ManAuto.PV', 'LQTF13_Open.PV', 'LQTF14_Close.PV', 'LQTF14_FBClose.PV', 'LQTF14_FBOpen.PV',
             'LQTF14_ManAuto.PV', 'LQTF14_Open.PV', 'LQTF15_Close.PV', 'LQTF15_FBClose.PV', 'LQTF15_FBOpen.PV',
             'LQTF15_ManAuto.PV', 'LQTF15_Open.PV', 'LQTF16_Close.PV', 'LQTF16_FBClose.PV', 'LQTF16_FBOpen.PV',
             'LQTF16_ManAuto.PV', 'LQTF16_Open.PV', 'LQTF2_Close.PV', 'LQTF2_FBClose.PV', 'LQTF2_FBOpen.PV',
             'LQTF2_ManAuto.PV', 'LQTF2_Open.PV', 'LQTF3_Close.PV', 'LQTF3_FBClose.PV', 'LQTF3_FBOpen.PV',
             'LQTF3_ManAuto.PV', 'LQTF3_Open.PV', 'LQTF4_Close.PV', 'LQTF4_FBClose.PV', 'LQTF4_FBOpen.PV',
             'LQTF4_ManAuto.PV', 'LQTF4_Open.PV', 'LQTF5_Close.PV', 'LQTF5_FBClose.PV', 'LQTF5_FBOpen.PV',
             'LQTF5_ManAuto.PV', 'LQTF5_Open.PV', 'LQTF6_Close.PV', 'LQTF6_FBClose.PV', 'LQTF6_FBOpen.PV',
             'LQTF6_ManAuto.PV', 'LQTF6_Open.PV', 'LQTF7_Close.PV', 'LQTF7_FBClose.PV', 'LQTF7_FBOpen.PV',
             'LQTF7_ManAuto.PV', 'LQTF7_Open.PV', 'LQTF8_Close.PV', 'LQTF8_FBClose.PV', 'LQTF8_FBOpen.PV',
             'LQTF8_ManAuto.PV', 'LQTF8_Open.PV', 'LQTF9_Close.PV', 'LQTF9_FBClose.PV', 'LQTF9_FBOpen.PV',
             'LQTF9_ManAuto.PV', 'LQTF9_Open.PV', 'LSGS_PH.PV', 'LSGS_PL.PV', 'LSGS_TH.PV', 'LSHS_PH.PV', 'LSHS_PL.PV',
             'LSHS_TH.PV', 'M1ADD_Cur1.PV', 'M1ADD_T.PV', 'M1FJSQ_P_SPD.PV', 'M1FJSQ_P_SPX.PV', 'M1HL_LowX1.PV',
             'M1HL_LowX10.PV', 'M1HL_LowX2.PV', 'M1HL_LowX3.PV', 'M1HL_LowX4.PV', 'M1HL_LowX5.PV', 'M1HL_LowX6.PV',
             'M1HL_LowX7.PV', 'M1HL_LowX8.PV', 'M1HL_LowX9.PV', 'M1HL_Tem_SPD1.PV', 'M1HL_Tem_SPD10.PV',
             'M1HL_Tem_SPD2.PV', 'M1HL_Tem_SPD3.PV', 'M1HL_Tem_SPD4.PV', 'M1HL_Tem_SPD5.PV', 'M1HL_Tem_SPD6.PV',
             'M1HL_Tem_SPD7.PV', 'M1HL_Tem_SPD8.PV', 'M1HL_Tem_SPD9.PV', 'M1HL_Tem_SPX1.PV', 'M1HL_Tem_SPX10.PV',
             'M1HL_Tem_SPX2.PV', 'M1HL_Tem_SPX3.PV', 'M1HL_Tem_SPX4.PV', 'M1HL_Tem_SPX5.PV', 'M1HL_Tem_SPX6.PV',
             'M1HL_Tem_SPX7.PV', 'M1HL_Tem_SPX8.PV', 'M1HL_Tem_SPX9.PV', 'M1LDB_Hz_Low.PV', 'M1LDGS_P_SP1.PV',
             'M1LDGS_P_SP2.PV', 'M1LDGS_P_SP3.PV', 'M1LDGS_P_SP4.PV', 'M1LDGS_P_SP5.PV', 'M1LDGS_P_SP6.PV',
             'M1LQB_Hz_Low.PV', 'M1RSB_Hz_Low.PV', 'M1RSGS_P_SP1.PV', 'M1RSGS_P_SP2.PV', 'M1RSGS_P_SP3.PV',
             'M1RSGS_Tem_SP.PV', 'M1SUB_Cur1.PV', 'M1SUB_T.PV', 'M1ZLJ_MAX.PV', 'M1ZLJ_MIN.PV', 'M1ZQF_Low.PV',
             'M2ADD_Cur1.PV', 'M2ADD_T.PV', 'M2FJSQ_P_SPD.PV', 'M2FJSQ_P_SPX.PV', 'M2HL_LowX1.PV', 'M2HL_LowX10.PV',
             'M2HL_LowX2.PV', 'M2HL_LowX3.PV', 'M2HL_LowX4.PV', 'M2HL_LowX5.PV', 'M2HL_LowX6.PV', 'M2HL_LowX7.PV',
             'M2HL_LowX8.PV', 'M2HL_LowX9.PV', 'M2HL_Tem_SPD1.PV', 'M2HL_Tem_SPD10.PV', 'M2HL_Tem_SPD2.PV',
             'M2HL_Tem_SPD3.PV', 'M2HL_Tem_SPD4.PV', 'M2HL_Tem_SPD5.PV', 'M2HL_Tem_SPD6.PV', 'M2HL_Tem_SPD7.PV',
             'M2HL_Tem_SPD8.PV', 'M2HL_Tem_SPD9.PV', 'M2HL_Tem_SPX1.PV', 'M2HL_Tem_SPX10.PV', 'M2HL_Tem_SPX2.PV',
             'M2HL_Tem_SPX3.PV', 'M2HL_Tem_SPX4.PV', 'M2HL_Tem_SPX5.PV', 'M2HL_Tem_SPX6.PV', 'M2HL_Tem_SPX7.PV',
             'M2HL_Tem_SPX8.PV', 'M2HL_Tem_SPX9.PV', 'M2LDB_Hz_Low.PV', 'M2LDGS_P_SP1.PV', 'M2LDGS_P_SP2.PV',
             'M2LDGS_P_SP3.PV', 'M2LDGS_P_SP4.PV', 'M2LDGS_P_SP5.PV', 'M2LDGS_P_SP6.PV', 'M2LQB_Hz_Low.PV',
             'M2RSB_Hz_Low.PV', 'M2RSGS_P_SP1.PV', 'M2RSGS_P_SP2.PV', 'M2RSGS_P_SP3.PV', 'M2RSGS_Tem_SP.PV',
             'M2SUB_Cur1.PV', 'M2SUB_T.PV', 'M2ZLJ_MAX.PV', 'M2ZLJ_MIN.PV', 'M2ZQF_Low.PV', 'M3ADD_Cur1.PV',
             'M3ADD_T.PV', 'M3FJSQ_P_SPD.PV', 'M3FJSQ_P_SPX.PV', 'M3HL_LowX1.PV', 'M3HL_LowX10.PV', 'M3HL_LowX2.PV',
             'M3HL_LowX3.PV', 'M3HL_LowX4.PV', 'M3HL_LowX5.PV', 'M3HL_LowX6.PV', 'M3HL_LowX7.PV', 'M3HL_LowX8.PV',
             'M3HL_LowX9.PV', 'M3HL_Tem_SPD1.PV', 'M3HL_Tem_SPD10.PV', 'M3HL_Tem_SPD2.PV', 'M3HL_Tem_SPD3.PV',
             'M3HL_Tem_SPD4.PV', 'M3HL_Tem_SPD5.PV', 'M3HL_Tem_SPD6.PV', 'M3HL_Tem_SPD7.PV', 'M3HL_Tem_SPD8.PV',
             'M3HL_Tem_SPD9.PV', 'M3HL_Tem_SPX1.PV', 'M3HL_Tem_SPX10.PV', 'M3HL_Tem_SPX2.PV', 'M3HL_Tem_SPX3.PV',
             'M3HL_Tem_SPX4.PV', 'M3HL_Tem_SPX5.PV', 'M3HL_Tem_SPX6.PV', 'M3HL_Tem_SPX7.PV', 'M3HL_Tem_SPX8.PV',
             'M3HL_Tem_SPX9.PV', 'M3LDB_Hz_Low.PV', 'M3LDGS_P_SP1.PV', 'M3LDGS_P_SP2.PV', 'M3LDGS_P_SP3.PV',
             'M3LDGS_P_SP4.PV', 'M3LDGS_P_SP5.PV', 'M3LDGS_P_SP6.PV', 'M3LQB_Hz_Low.PV', 'M3RSB_Hz_Low.PV',
             'M3RSGS_P_SP1.PV', 'M3RSGS_P_SP2.PV', 'M3RSGS_P_SP3.PV', 'M3RSGS_Tem_SP.PV', 'M3SUB_Cur1.PV', 'M3SUB_T.PV',
             'M3ZLJ_MAX.PV', 'M3ZLJ_MIN.PV', 'M3ZQF_Low.PV', 'M4ADD_Cur1.PV', 'M4ADD_T.PV', 'M4FJSQ_P_SPD.PV',
             'M4FJSQ_P_SPX.PV', 'M4HL_LowX1.PV', 'M4HL_LowX10.PV', 'M4HL_LowX2.PV', 'M4HL_LowX3.PV', 'M4HL_LowX4.PV',
             'M4HL_LowX5.PV', 'M4HL_LowX6.PV', 'M4HL_LowX7.PV', 'M4HL_LowX8.PV', 'M4HL_LowX9.PV', 'M4HL_Tem_SPD1.PV',
             'M4HL_Tem_SPD10.PV', 'M4HL_Tem_SPD2.PV', 'M4HL_Tem_SPD3.PV', 'M4HL_Tem_SPD4.PV', 'M4HL_Tem_SPD5.PV',
             'M4HL_Tem_SPD6.PV', 'M4HL_Tem_SPD7.PV', 'M4HL_Tem_SPD8.PV', 'M4HL_Tem_SPD9.PV', 'M4HL_Tem_SPX1.PV',
             'M4HL_Tem_SPX10.PV', 'M4HL_Tem_SPX2.PV', 'M4HL_Tem_SPX3.PV', 'M4HL_Tem_SPX4.PV', 'M4HL_Tem_SPX5.PV',
             'M4HL_Tem_SPX6.PV', 'M4HL_Tem_SPX7.PV', 'M4HL_Tem_SPX8.PV', 'M4HL_Tem_SPX9.PV', 'M4LDB_Hz_Low.PV',
             'M4LDGS_P_SP1.PV', 'M4LDGS_P_SP2.PV', 'M4LDGS_P_SP3.PV', 'M4LDGS_P_SP4.PV', 'M4LDGS_P_SP5.PV',
             'M4LDGS_P_SP6.PV', 'M4LQB_Hz_Low.PV', 'M4RSB_Hz_Low.PV', 'M4RSGS_P_SP1.PV', 'M4RSGS_P_SP2.PV',
             'M4RSGS_P_SP3.PV', 'M4RSGS_Tem_SP.PV', 'M4SUB_Cur1.PV', 'M4SUB_T.PV', 'M4ZLJ_MAX.PV', 'M4ZLJ_MIN.PV',
             'M4ZQF_Low.PV', 'MA1.PV', 'MA2.PV', 'MA3.PV', 'MA4.PV', 'MA5.PV', 'MA6.PV', 'MA7.PV', 'MA8.PV',
             'MADD_Cur2.PV', 'MAdd_Pan1.PV', 'MAdd_Pan2.PV', 'MAddDelay.PV', 'MADDSUB_Time1.PV', 'MADDSUB_Time2.PV',
             'MAutoStart.PV', 'MAutoStartR.PV', 'MB1.PV', 'MB2.PV', 'MB3.PV', 'MB4.PV', 'MB5.PV', 'MB6.PV', 'MB7.PV',
             'MB8.PV', 'MBAN_Auto.PV', 'MBG_Time.PV', 'MBPWDD.PV', 'MBPWDX.PV', 'MC1.PV', 'MC2.PV', 'MC3.PV', 'MC4.PV',
             'MC5.PV', 'MC6.PV', 'MC7.PV', 'MC8.PV', 'MChuShi_EN.PV', 'MCKWD.PV', 'MCom_Error1.PV', 'MCom_Error2.PV',
             'MCom_Error3.PV', 'MCom_Error4.PV', 'MCom_Error5.PV', 'MCom_Error6.PV', 'MCom_Error7.PV', 'MCom_Error8.PV',
             'MCOP.PV', 'MCS_Delay1.PV', 'MCS_Delay2.PV', 'MD1.PV', 'MD2.PV', 'MD3.PV', 'MD4.PV', 'MD5.PV', 'MD6.PV',
             'MD7.PV', 'MD8.PV', 'MDDC_Day.PV', 'MDDC_Hour.PV', 'MDDC_Minute.PV', 'MDDC_Month.PV', 'MDDC_Week.PV',
             'MDDC_Year.PV', 'MFJ3_KWh.PV', 'MFJ3_ManAuto.PV', 'MFJ3_ManOn.PV', 'MFJ3_Mode.PV', 'MFJ3_NeedRep.PV',
             'MFJ3_Repair.PV', 'MFJ3_RepTime.PV', 'MFJ3_Run.PV', 'MFJ3_RunTime.PV', 'MFJ4_A.PV', 'MFJ4_Alarm.PV',
             'MFJ4_Clear.PV', 'MFJ4_Fre_FB.PV', 'MFJ4_FreSP.PV', 'MFJ4_KW.PV', 'MFJ4_KWh.PV', 'MFJ4_ManAuto.PV',
             'MFJ4_ManOn.PV', 'MFJ4_Mode.PV', 'MFJ4_NeedRep.PV', 'MFJ4_Repair.PV', 'MFJ4_RepTime.PV', 'MFJ4_Run.PV',
             'MFJ4_RunTime.PV', 'MFJ5_A.PV', 'MFJ5_Alarm.PV', 'MFJ5_Clear.PV', 'MFJ5_Fre_FB.PV', 'MFJ5_FreSP.PV',
             'MFJ5_KW.PV', 'MFJ5_KWh.PV', 'MFJ5_ManAuto.PV', 'MFJ5_ManOn.PV', 'MFJ5_Mode.PV', 'MFJ5_NeedRep.PV',
             'MFJ5_Repair.PV', 'MFJ5_RepTime.PV', 'MFJ5_Run.PV', 'MFJ5_RunTime.PV', 'MFJ6_A.PV', 'MFJ6_Alarm.PV',
             'MFJ6_Clear.PV', 'MFJ6_Fre_FB.PV', 'MFJ6_FreSP.PV', 'MFJ6_KW.PV', 'MFJ6_KWh.PV', 'MFJ6_ManAuto.PV',
             'MFJ6_ManOn.PV', 'MFJ6_Mode.PV', 'MFJ6_NeedRep.PV', 'MFJ6_Repair.PV', 'MFJ6_RepTime.PV', 'MFJ6_Run.PV',
             'MFJ6_RunTime.PV', 'MFJ7_A.PV', 'MFJ7_Alarm.PV', 'MFJ7_Clear.PV', 'MFJ7_Fre_FB.PV', 'MFJ7_FreSP.PV',
             'MFJ7_KW.PV', 'MFJ7_KWh.PV', 'MFJ7_ManAuto.PV', 'MFJ7_ManOn.PV', 'MFJ7_Mode.PV', 'MFJ7_NeedRep.PV',
             'MFJ7_Repair.PV', 'MFJ7_RepTime.PV', 'MFJ7_Run.PV', 'MFJ7_RunTime.PV', 'MFJ8_A.PV', 'MFJ8_Alarm.PV',
             'MFJ8_Clear.PV', 'MFJ8_Fre_FB.PV', 'MFJ8_FreSP.PV', 'MFJ8_KW.PV', 'MFJ8_KWh.PV', 'MFJ8_ManAuto.PV',
             'MFJ8_ManOn.PV', 'MFJ8_Mode.PV', 'MFJ8_NeedRep.PV', 'MFJ8_Repair.PV', 'MFJ8_RepTime.PV', 'MFJ8_Run.PV',
             'MFJ8_RunTime.PV', 'MFJ9_Alarm.PV', 'MFJ9_Clear.PV', 'MFJ9_Fre_FB.PV', 'MFJ9_FreSP.PV', 'MFJ9_ManAuto.PV',
             'MFJ9_ManOn.PV', 'MFJ9_Mode.PV', 'MFJ9_NeedRep.PV', 'MFJ9_Repair.PV', 'MFJ9_RepTime.PV', 'MFJ9_Run.PV',
             'MFJ9_RunTime.PV', 'MFM_CloseTime1.PV', 'MFM_CloseTime2.PV', 'MFM_CloseTime3.PV', 'MFM_CloseTime4.PV',
             'MFM_CloseTime5.PV', 'MFM_CloseTime6.PV', 'MFM_OpenTime1.PV', 'MFM_OpenTime2.PV', 'MFM_OpenTime3.PV',
             'MFM_OpenTime4.PV', 'MFM_OpenTime5.PV', 'MFM_OpenTime6.PV', 'MFSQ_Press1.PV', 'MFSQ_Press2.PV', 'MG1.PV',
             'MG2.PV', 'MG3.PV', 'MG4.PV', 'MG5.PV', 'MG6.PV', 'MG7.PV', 'MG8.PV', 'MGL_DNB1.PV', 'MGL_KW.PV',
             'MGL_KWh.PV', 'MGL1_A.PV', 'MGL1_Alarm.PV', 'MGL1_ChuShi.PV', 'MGL1_Clear.PV', 'MGL1_KW.PV', 'MGL1_KWh.PV',
             'MGL1_ManAuto.PV', 'MGL1_ManOn.PV', 'MGL1_Mode.PV', 'MGL1_NeedRep.PV', 'MGL1_Repair.PV', 'MGL1_RepTime.PV',
             'MGL1_Run.PV', 'MGL1_RunTime.PV', 'MGL2_A.PV', 'MGL2_Alarm.PV', 'MGL2_ChuShi.PV', 'MGL2_Clear.PV',
             'MGL2_KW.PV', 'MGL2_KWh.PV', 'MGL2_ManAuto.PV', 'MGL2_ManOn.PV', 'MGL2_Mode.PV', 'MGL2_NeedRep.PV',
             'MGL2_Repair.PV', 'MGL2_RepTime.PV', 'MGL2_Run.PV', 'MGL2_RunTime.PV', 'MGL3_A.PV', 'MGL3_Alarm.PV',
             'MGL3_ChuShi.PV', 'MGL3_Clear.PV', 'MGL3_KW.PV', 'MGL3_KWh.PV', 'MECB6_FreSP.PV', 'MECB6_KW.PV',
             'MECB6_KWh.PV', 'MECB6_ManAuto.PV', 'MECB6_ManOn.PV', 'MECB6_Mode.PV', 'MECB6_NeedRep.PV',
             'MECB6_Repair.PV', 'MECB6_RepTime.PV', 'MECB6_Run.PV', 'MECB6_RunTime.PV', 'MECRB_DB.PV', 'MECRB_DNB1.PV',
             'MECRB_HighSP1.PV', 'MECRB_I.PV', 'MECRB_KW.PV', 'MECRB_KWh.PV', 'MECRB_P.PV', 'MECRB1_A.PV',
             'MECRB1_Alarm.PV', 'MECRB1_Clear.PV', 'MECRB1_Fre_FB.PV', 'MECRB1_FreSP.PV', 'MECRB1_KW.PV',
             'MECRB1_KWh.PV', 'MECRB1_ManAuto.PV', 'MECRB1_ManOn.PV', 'MECRB1_Mode.PV', 'MECRB1_NeedRep.PV',
             'MECRB1_Repair.PV', 'MECRB1_RepTime.PV', 'MECRB1_Run.PV', 'MECRB1_RunTime.PV', 'MECRB2_A.PV',
             'MECRB2_Alarm.PV', 'MECRB2_Clear.PV', 'MECRB2_Fre_FB.PV', 'MECRB2_FreSP.PV', 'MECRB2_KW.PV',
             'MECRB2_KWh.PV', 'MECRB2_ManAuto.PV', 'MECRB2_ManOn.PV', 'MECRB2_Mode.PV', 'MECRB2_NeedRep.PV',
             'MECRB2_Repair.PV', 'MECRB2_RepTime.PV', 'MECRB2_Run.PV', 'MECRB2_RunTime.PV', 'MECRB3_A.PV',
             'MECRB3_Alarm.PV', 'MECRB3_Clear.PV', 'MECRB3_Fre_FB.PV', 'MECRB3_FreSP.PV', 'MECRB3_KW.PV',
             'MECRB3_KWh.PV', 'MECRB3_ManAuto.PV', 'MECRB3_ManOn.PV', 'MECRB3_Mode.PV', 'MECRB3_NeedRep.PV',
             'MECRB3_Repair.PV', 'MECRB3_RepTime.PV', 'MECRB3_Run.PV', 'MECRB3_RunTime.PV', 'MECRB4_A.PV',
             'MECRB4_Alarm.PV', 'MECRB4_Clear.PV', 'MECRB4_Fre_FB.PV', 'MECRB4_FreSP.PV', 'MECRB4_KW.PV',
             'MECRB4_KWh.PV', 'MECRB4_ManAuto.PV', 'MECRB4_ManOn.PV', 'MECRB4_Mode.PV', 'MECRB4_NeedRep.PV',
             'MECRB4_Repair.PV', 'MECRB4_RepTime.PV', 'MECRB4_Run.PV', 'MECRB4_RunTime.PV', 'MECRB5_A.PV',
             'MECRB5_Alarm.PV', 'MECRB5_Clear.PV', 'MECRB5_Fre_FB.PV', 'MECRB5_FreSP.PV', 'MECRB5_KW.PV',
             'MECRB5_KWh.PV', 'MECRB5_ManAuto.PV', 'MECRB5_ManOn.PV', 'MECRB5_Mode.PV', 'MECRB5_NeedRep.PV',
             'MECRB5_Repair.PV', 'MECRB5_RepTime.PV', 'MECRB5_Run.PV', 'MECRB5_RunTime.PV', 'MECRB6_A.PV',
             'MECRB6_Alarm.PV', 'MECRB6_Clear.PV', 'MECRB6_Fre_FB.PV', 'MECRB6_FreSP.PV', 'MECRB6_KW.PV',
             'MECRB6_KWh.PV', 'MECRB6_ManAuto.PV', 'MECRB6_ManOn.PV', 'MECRB6_Mode.PV', 'MECRB6_NeedRep.PV',
             'MECRB6_Repair.PV', 'MECRB6_RepTime.PV', 'MECRB6_Run.PV', 'MECRB6_RunTime.PV', 'MF1.PV', 'MF2.PV',
             'MF3.PV', 'MF4.PV', 'MF5.PV', 'MF6.PV', 'MF7.PV', 'MF8.PV', 'MFJ_Burst1.PV', 'MFJ_Burst2.PV',
             'MFJ_Burst3.PV', 'MFJ_BurstTem1.PV', 'MFJ_BurstTem2.PV', 'MFJ_BurstTem3.PV', 'MFJ_CsNum1.PV',
             'MFJ_CsNum2.PV', 'MFJ_CsNum3.PV', 'MFJ_DB.PV', 'MFJ_DbSP1.PV', 'MFJ_DbSP2.PV', 'MFJ_DbSP3.PV',
             'MFJ_DNB1.PV', 'MFJ_I.PV', 'MFJ_KW.PV', 'MFJ_KWh.PV', 'MFJ_MAX1.PV', 'MFJ_MAX2.PV', 'MFJ_MAX3.PV',
             'MFJ_P.PV', 'MFJ_TemSP1.PV', 'MFJ_TemSP2.PV', 'MFJ_TemSP3.PV', 'MFJ_ZhouQi1.PV', 'MFJ_ZhouQi2.PV',
             'MFJ_ZhouQi3.PV', 'MFJ1_A.PV', 'MFJ1_Alarm.PV', 'MFJ1_Clear.PV', 'MFJ1_Fre_FB.PV', 'MFJ1_FreSP.PV',
             'MFJ1_KW.PV', 'MFJ1_KWh.PV', 'MFJ1_ManAuto.PV', 'MFJ1_ManOn.PV', 'MFJ1_Mode.PV', 'MFJ1_NeedRep.PV',
             'MFJ1_Repair.PV', 'MFJ1_RepTime.PV', 'MFJ1_Run.PV', 'MFJ1_RunTime.PV', 'MFJ10_Alarm.PV', 'MFJ10_Clear.PV',
             'MFJ10_Fre_FB.PV', 'MFJ10_FreSP.PV', 'MFJ10_ManAuto.PV', 'MFJ10_ManOn.PV', 'MFJ10_Mode.PV',
             'MFJ10_NeedRep.PV', 'MFJ10_Repair.PV', 'MFJ10_RepTime.PV', 'MFJ10_Run.PV', 'MFJ10_RunTime.PV',
             'MFJ11_Alarm.PV', 'MFJ11_Clear.PV', 'MFJ11_Fre_FB.PV', 'MFJ11_FreSP.PV', 'MFJ11_ManAuto.PV',
             'MFJ11_ManOn.PV', 'MFJ11_Mode.PV', 'MFJ11_NeedRep.PV', 'MFJ11_Repair.PV', 'MFJ11_RepTime.PV',
             'MFJ11_Run.PV', 'MFJ11_RunTime.PV', 'MFJ12_Alarm.PV', 'MFJ12_Clear.PV', 'MFJ12_Fre_FB.PV',
             'MFJ12_FreSP.PV', 'MFJ12_ManAuto.PV', 'MFJ12_ManOn.PV', 'MFJ12_Mode.PV', 'MFJ12_NeedRep.PV',
             'MFJ12_Repair.PV', 'MFJ12_RepTime.PV', 'MFJ12_Run.PV', 'MFJ12_RunTime.PV', 'MFJ13_Alarm.PV',
             'MFJ13_Clear.PV', 'MFJ13_Fre_FB.PV', 'MFJ13_FreSP.PV', 'MFJ13_ManAuto.PV', 'MFJ13_ManOn.PV',
             'MFJ13_Mode.PV', 'MFJ13_NeedRep.PV', 'MFJ13_Repair.PV', 'MFJ13_RepTime.PV', 'MFJ13_Run.PV',
             'MFJ13_RunTime.PV', 'MFJ14_Alarm.PV', 'MFJ14_Clear.PV', 'MFJ14_Fre_FB.PV', 'MFJ14_FreSP.PV',
             'MFJ14_ManAuto.PV', 'MFJ14_ManOn.PV', 'MFJ14_Mode.PV', 'MFJ14_NeedRep.PV', 'MFJ14_Repair.PV',
             'MFJ14_RepTime.PV', 'MFJ14_Run.PV', 'MFJ14_RunTime.PV', 'MFJ15_Alarm.PV', 'MFJ15_Clear.PV',
             'MFJ15_Fre_FB.PV', 'MFJ15_FreSP.PV', 'MFJ15_ManAuto.PV', 'MFJ15_ManOn.PV', 'MFJ15_Mode.PV',
             'MFJ15_NeedRep.PV', 'MFJ15_Repair.PV', 'MFJ15_RepTime.PV', 'MFJ15_Run.PV', 'MFJ15_RunTime.PV',
             'MFJ16_Alarm.PV', 'MFJ16_Clear.PV', 'MFJ16_Fre_FB.PV', 'MFJ16_FreSP.PV', 'MFJ16_ManAuto.PV',
             'MFJ16_ManOn.PV', 'MFJ16_Mode.PV', 'MFJ16_NeedRep.PV', 'MFJ16_Repair.PV', 'MFJ16_RepTime.PV',
             'MFJ16_Run.PV', 'MFJ16_RunTime.PV', 'MFJ2_A.PV', 'MFJ2_Alarm.PV', 'MFJ2_Clear.PV', 'MFJ2_Fre_FB.PV',
             'MFJ2_FreSP.PV', 'MFJ2_KW.PV', 'MFJ2_KWh.PV', 'MFJ2_ManAuto.PV', 'MFJ2_ManOn.PV', 'MFJ2_Mode.PV',
             'MFJ2_NeedRep.PV', 'MFJ2_Repair.PV', 'MFJ2_RepTime.PV', 'MFJ2_Run.PV', 'MFJ2_RunTime.PV', 'MFJ3_A.PV',
             'MFJ3_Alarm.PV', 'MFJ3_Clear.PV', 'MFJ3_Fre_FB.PV', 'MFJ3_FreSP.PV', 'MFJ3_KW.PV', 'MLDB3_KW.PV',
             'MLDB3_KWh.PV', 'MLDB3_ManAuto.PV', 'MLDB3_ManOn.PV', 'MLDB3_Mode.PV', 'MLDB3_NeedRep.PV',
             'MLDB3_Repair.PV', 'MLDB3_RepTime.PV', 'MLDB3_Run.PV', 'MLDB3_RunTime.PV', 'MLDB4_A.PV', 'MLDB4_Alarm.PV',
             'MLDB4_Clear.PV', 'MLDB4_Fre_FB.PV', 'MLDB4_FreSP.PV', 'MLDB4_KW.PV', 'MLDB4_KWh.PV', 'MLDB4_ManAuto.PV',
             'MLDB4_ManOn.PV', 'MLDB4_Mode.PV', 'MLDB4_NeedRep.PV', 'MLDB4_Repair.PV', 'MLDB4_RepTime.PV',
             'MLDB4_Run.PV', 'MLDB4_RunTime.PV', 'MLDB5_A.PV', 'MLDB5_Alarm.PV', 'MLDB5_Clear.PV', 'MLDB5_Fre_FB.PV',
             'MLDB5_FreSP.PV', 'MLDB5_KW.PV', 'MLDB5_KWh.PV', 'MLDB5_ManAuto.PV', 'MLDB5_ManOn.PV', 'MLDB5_Mode.PV',
             'MLDB5_NeedRep.PV', 'MLDB5_Repair.PV', 'MLDB5_RepTime.PV', 'MLDB5_Run.PV', 'MLDB5_RunTime.PV',
             'MLDB6_A.PV', 'MLDB6_Alarm.PV', 'MLDB6_Clear.PV', 'MLDB6_Fre_FB.PV', 'MLDB6_FreSP.PV', 'MLDB6_KW.PV',
             'MLDB6_KWh.PV', 'MLDB6_ManAuto.PV', 'MLDB6_ManOn.PV', 'MLDB6_Mode.PV', 'MLDB6_NeedRep.PV',
             'MLDB6_Repair.PV', 'MLDB6_RepTime.PV', 'MLDB6_Run.PV', 'MLDB6_RunTime.PV', 'MLDB7_A.PV', 'MLDB7_Alarm.PV',
             'MLDB7_Clear.PV', 'MLDB7_Fre_FB.PV', 'MLDB7_FreSP.PV', 'MLDB7_KW.PV', 'MLDB7_KWh.PV', 'MLDB7_ManAuto.PV',
             'MLDB7_ManOn.PV', 'MLDB7_Mode.PV', 'MLDB7_NeedRep.PV', 'MLDB7_Repair.PV', 'MLDB7_RepTime.PV',
             'MLDB7_Run.PV', 'MLDB7_RunTime.PV', 'MLDB8_A.PV', 'MLDB8_Alarm.PV', 'MLDB8_Clear.PV', 'MLDB8_Fre_FB.PV',
             'MLDB8_FreSP.PV', 'MLDB8_KW.PV', 'MLDB8_KWh.PV', 'MLDB8_ManAuto.PV', 'MLDB8_ManOn.PV', 'MLDB8_Mode.PV',
             'MLDB8_NeedRep.PV', 'MLDB8_Repair.PV', 'MLDB8_RepTime.PV', 'MLDB8_Run.PV', 'MLDB8_RunTime.PV',
             'MLDF_Stop1.PV', 'MLDF_Stop2.PV', 'MLDF_Stop3.PV', 'MLDF_Stop4.PV', 'MLDF_Stop5.PV', 'MLDF_Stop6.PV',
             'MLDF1_Close.PV', 'MLDF1_FBClose.PV', 'MLDF1_FBOpen.PV', 'MLDF1_ManAuto.PV', 'MLDF1_Open.PV',
             'MLDF2_Close.PV', 'MLDF2_FBClose.PV', 'MLDF2_FBOpen.PV', 'MLDF2_ManAuto.PV', 'MLDF2_Open.PV',
             'MLDF3_Close.PV', 'MLDF3_FBClose.PV', 'MLDF3_FBOpen.PV', 'MLDF3_ManAuto.PV', 'MLDF3_Open.PV',
             'MLDF4_Close.PV', 'MLDF4_FBClose.PV', 'MLDF4_FBOpen.PV', 'MLDF4_ManAuto.PV', 'MLDF4_Open.PV',
             'MLDF5_Close.PV', 'MLDF5_FBClose.PV', 'MLDF5_FBOpen.PV', 'MLDF5_ManAuto.PV', 'MLDF5_Open.PV',
             'MLDF6_Close.PV', 'MLDF6_FBClose.PV', 'MLDF6_FBOpen.PV', 'MLDF6_ManAuto.PV', 'MLDF6_Open.PV',
             'MLDGS1_Tem.PV', 'MLDGS2_Tem.PV', 'MLDHS1_Tem.PV', 'MLDHS2_Tem.PV', 'MLDZG1_Flow.PV', 'MLDZG2_Flow.PV',
             'MLengReLiang.PV', 'MLLLJ.PV', 'MLOAD.PV', 'MLQB_DB.PV', 'MLQB_DNB1.PV', 'MLQB_HighSP1.PV', 'MLQB_I.PV',
             'MLQB_KW.PV', 'MLQB_KWh.PV', 'MLQB_P.PV', 'MLQB1_A.PV', 'MLQB1_Alarm.PV', 'MLQB1_Clear.PV',
             'MLQB1_Fre_FB.PV', 'MLQB1_FreSP.PV', 'MLQB1_KW.PV', 'MLQB1_KWh.PV', 'MLQB1_ManAuto.PV', 'MLQB1_ManOn.PV',
             'MLQB1_Mode.PV', 'MLQB1_NeedRep.PV', 'MLQB1_Repair.PV', 'MLQB1_RepTime.PV', 'MLQB1_Run.PV',
             'MLQB1_RunTime.PV', 'MLQB2_A.PV', 'MLQB2_Alarm.PV', 'MLQB2_Clear.PV', 'MLQB2_Fre_FB.PV', 'MLQB2_FreSP.PV',
             'MLQB2_KW.PV', 'MLQB2_KWh.PV', 'MLQB2_ManAuto.PV', 'MLQB2_ManOn.PV', 'MLQB2_Mode.PV', 'MLQB2_NeedRep.PV',
             'MLQB2_Repair.PV', 'MLQB2_RepTime.PV', 'MLQB2_Run.PV', 'MLQB2_RunTime.PV', 'MLQB3_A.PV', 'MLQB3_Alarm.PV',
             'MLQB3_Clear.PV', 'MLQB3_Fre_FB.PV', 'MLQB3_FreSP.PV', 'MLQB3_KW.PV', 'MLQB3_KWh.PV', 'MLQB3_ManAuto.PV',
             'MLQB3_ManOn.PV', 'MLQB3_Mode.PV', 'MLQB3_NeedRep.PV', 'MLQB3_Repair.PV', 'MLQB3_RepTime.PV',
             'MLQB3_Run.PV', 'MLQB3_RunTime.PV', 'MLQB4_A.PV', 'MLQB4_Alarm.PV', 'MLQB4_Clear.PV', 'MLQB4_Fre_FB.PV',
             'MLQB4_FreSP.PV', 'MLQB4_KW.PV', 'MLQB4_KWh.PV', 'MLQB4_ManAuto.PV', 'MLQB4_ManOn.PV', 'MLQB4_Mode.PV',
             'MLQB4_NeedRep.PV', 'MLQB4_Repair.PV', 'MLQB4_RepTime.PV', 'MLQB4_Run.PV', 'MGL3_ManAuto.PV',
             'MGL3_ManOn.PV', 'MGL3_Mode.PV', 'MGL3_NeedRep.PV', 'MGL3_Repair.PV', 'MGL3_RepTime.PV', 'MGL3_Run.PV',
             'MGL3_RunTime.PV', 'MGL4_A.PV', 'MGL4_Alarm.PV', 'MGL4_ChuShi.PV', 'MGL4_Clear.PV', 'MGL4_KW.PV',
             'MGL4_KWh.PV', 'MGL4_ManAuto.PV', 'MGL4_ManOn.PV', 'MGL4_Mode.PV', 'MGL4_NeedRep.PV', 'MGL4_Repair.PV',
             'MGL4_RepTime.PV', 'MGL4_Run.PV', 'MGL4_RunTime.PV', 'MGongKuang_EN.PV', 'MGongPing.PV', 'MGPWDD.PV',
             'MGPWDX.PV', 'MH1.PV', 'MH2.PV', 'MH3.PV', 'MH4.PV', 'MH5.PV', 'MH6.PV', 'MH7.PV', 'MH8.PV',
             'MHL1_BuChang.PV', 'MHL1_BuChangSP.PV', 'MHL1_Flow.PV', 'MHL1_WenBian.PV', 'MHL1_YuQi_Tem.PV',
             'MHL1_ZhouQi.PV', 'MHL10_BuChang.PV', 'MHL10_BuChangSP.PV', 'MHL10_Flow.PV', 'MHL10_WenBian.PV',
             'MHL10_YuQi_Tem.PV', 'MHL10_ZhouQi.PV', 'MHL10HS_Press.PV', 'MHL10HS_Tem.PV', 'MHL1HS_Press.PV',
             'MHL1HS_Tem.PV', 'MHL2_BuChang.PV', 'MHL2_BuChangSP.PV', 'MHL2_Flow.PV', 'MHL2_WenBian.PV',
             'MHL2_YuQi_Tem.PV', 'MHL2_ZhouQi.PV', 'MHL2HS_Press.PV', 'MHL2HS_Tem.PV', 'MHL3_BuChang.PV',
             'MHL3_BuChangSP.PV', 'MHL3_Flow.PV', 'MHL3_WenBian.PV', 'MHL3_YuQi_Tem.PV', 'MHL3_ZhouQi.PV',
             'MHL3HS_Press.PV', 'MHL3HS_Tem.PV', 'MHL4_BuChang.PV', 'MHL4_BuChangSP.PV', 'MHL4_Flow.PV',
             'MHL4_WenBian.PV', 'MHL4_YuQi_Tem.PV', 'MHL4_ZhouQi.PV', 'MHL4HS_Press.PV', 'MHL4HS_Tem.PV',
             'MHL5_BuChang.PV', 'MHL5_BuChangSP.PV', 'MHL5_Flow.PV', 'MHL5_WenBian.PV', 'MHL5_YuQi_Tem.PV',
             'MHL5_ZhouQi.PV', 'MHL5HS_Press.PV', 'MHL5HS_Tem.PV', 'MHL6_BuChang.PV', 'MHL6_BuChangSP.PV',
             'MHL6_Flow.PV', 'MHL6_WenBian.PV', 'MHL6_YuQi_Tem.PV', 'MHL6_ZhouQi.PV', 'MHL6HS_Press.PV',
             'MHL6HS_Tem.PV', 'MHL7_BuChang.PV', 'MHL7_BuChangSP.PV', 'MHL7_Flow.PV', 'MHL7_WenBian.PV',
             'MHL7_YuQi_Tem.PV', 'MHL7_ZhouQi.PV', 'MHL7HS_Press.PV', 'MHL7HS_Tem.PV', 'MHL8_BuChang.PV',
             'MHL8_BuChangSP.PV', 'MHL8_Flow.PV', 'MHL8_WenBian.PV', 'MHL8_YuQi_Tem.PV', 'MHL8_ZhouQi.PV',
             'MHL8HS_Press.PV', 'MHL8HS_Tem.PV', 'MHL9_BuChang.PV', 'MHL9_BuChangSP.PV', 'MHL9_Flow.PV',
             'MHL9_WenBian.PV', 'MHL9_YuQi_Tem.PV', 'MHL9_ZhouQi.PV', 'MHL9HS_Press.PV', 'MHL9HS_Tem.PV', 'MHLF_DB.PV',
             'MHLF_EN1.PV', 'MHLF_EN10.PV', 'MHLF_EN2.PV', 'MHLF_EN3.PV', 'MHLF_EN4.PV', 'MHLF_EN5.PV', 'MHLF_EN6.PV',
             'MHLF_EN7.PV', 'MHLF_EN8.PV', 'MHLF_EN9.PV', 'MHLF_I.PV', 'MHLF_P.PV', 'MHLF1_FB.PV', 'MHLF1_ManAuto.PV',
             'MHLF1_OutSP.PV', 'MHLF10_FB.PV', 'MHLF10_ManAuto.PV', 'MHLF10_OutSP.PV', 'MHLF2_FB.PV',
             'MHLF2_ManAuto.PV', 'MHLF2_OutSP.PV', 'MHLF3_FB.PV', 'MHLF3_ManAuto.PV', 'MHLF3_OutSP.PV', 'MHLF4_FB.PV',
             'MHLF4_ManAuto.PV', 'MHLF4_OutSP.PV', 'MHLF5_FB.PV', 'MHLF5_ManAuto.PV', 'MHLF5_OutSP.PV', 'MHLF6_FB.PV',
             'MHLF6_ManAuto.PV', 'MHLF6_OutSP.PV', 'MHLF7_FB.PV', 'MHLF7_ManAuto.PV', 'MHLF7_OutSP.PV', 'MHLF8_FB.PV',
             'MHLF8_ManAuto.PV', 'MHLF8_OutSP.PV', 'MHLF9_FB.PV', 'MHLF9_ManAuto.PV', 'MHLF9_OutSP.PV', 'MHLKD_H1.PV',
             'MHLKD_H10.PV', 'MHLKD_H2.PV', 'MHLKD_H3.PV', 'MHLKD_H4.PV', 'MHLKD_H5.PV', 'MHLKD_H6.PV', 'MHLKD_H7.PV',
             'MHLKD_H8.PV', 'MHLKD_H9.PV', 'MHLKD_L1.PV', 'MHLKD_L10.PV', 'MHLKD_L2.PV', 'MHLKD_L3.PV', 'MHLKD_L4.PV',
             'MHLKD_L5.PV', 'MHLKD_L6.PV', 'MHLKD_L7.PV', 'MHLKD_L8.PV', 'MHLKD_L9.PV', 'MHLKD_M1.PV', 'MHLKD_M10.PV',
             'MHLKD_M2.PV', 'MHLKD_M3.PV', 'MHLKD_M4.PV', 'MHLKD_M5.PV', 'MHLKD_M6.PV', 'MHLKD_M7.PV', 'MHLKD_M8.PV',
             'MHLKD_M9.PV', 'MHz_H.PV', 'MHz_L.PV', 'MHz_M.PV', 'MI1.PV', 'MI2.PV', 'MI3.PV', 'MI4.PV', 'MI5.PV',
             'MI6.PV', 'MI7.PV', 'MI8.PV', 'MJ1.PV', 'MJ2.PV', 'MJ3.PV', 'MJ4.PV', 'MJ5.PV', 'MJ6.PV', 'MJ7.PV',
             'MJ8.PV', 'MJiJieMode.PV', 'MJSQ_Press1.PV', 'MJSQ_Press2.PV', 'MLDB_DB.PV', 'MLDB_DNB1.PV',
             'MLDB_HighSP1.PV', 'MLDB_I.PV', 'MLDB_KW.PV', 'MLDB_KWh.PV', 'MLDB_OffTime1.PV', 'MLDB_OffTime2.PV',
             'MLDB_OffTime3.PV', 'MLDB_OffTime4.PV', 'MLDB_OffTime5.PV', 'MLDB_OffTime6.PV', 'MLDB_OnTime1.PV',
             'MLDB_OnTime2.PV', 'MLDB_OnTime3.PV', 'MLDB_OnTime4.PV', 'MLDB_OnTime5.PV', 'MLDB_OnTime6.PV', 'MLDB_P.PV',
             'MLDB1_A.PV', 'MLDB1_Alarm.PV', 'MLDB1_Clear.PV', 'MLDB1_Fre_FB.PV', 'MLDB1_FreSP.PV', 'MLDB1_KW.PV',
             'MLDB1_KWh.PV', 'MLDB1_ManAuto.PV', 'MLDB1_ManOn.PV', 'MLDB1_Mode.PV', 'MLDB1_NeedRep.PV',
             'MLDB1_Repair.PV', 'MLDB1_RepTime.PV', 'MLDB1_Run.PV', 'MLDB1_RunTime.PV', 'MLDB2_A.PV', 'MLDB2_Alarm.PV',
             'MLDB2_Clear.PV', 'MLDB2_Fre_FB.PV', 'MLDB2_FreSP.PV', 'MLDB2_KW.PV', 'MLDB2_KWh.PV', 'MLDB2_ManAuto.PV',
             'MLDB2_ManOn.PV', 'MLDB2_Mode.PV', 'MLDB2_NeedRep.PV', 'MLDB2_Repair.PV', 'MLDB2_RepTime.PV',
             'MLDB2_Run.PV', 'MLDB2_RunTime.PV', 'MLDB3_A.PV', 'MLDB3_Alarm.PV', 'MLDB3_Clear.PV', 'MLDB3_Fre_FB.PV',
             'MLDB3_FreSP.PV', 'MWeekEn7.PV', 'MXT_H.PV', 'MXT_H1.PV', 'MXT_L.PV', 'MXT_L1.PV', 'MXT_M.PV', 'MXT_M1.PV',
             'MXTZ_KW.PV', 'MXTZ_KWh.PV', 'MXTZR_KW.PV', 'MXTZR_KWh.PV', 'MYC_SP1.PV', 'MYC_SP10.PV', 'MYC_SP2.PV',
             'MYC_SP3.PV', 'MYC_SP4.PV', 'MYC_SP5.PV', 'MYC_SP6.PV', 'MYC_SP7.PV', 'MYC_SP8.PV', 'MYC_SP9.PV',
             'MZLJ_DNB1.PV', 'MZLJ_ENAuto.PV', 'MZLJ_KW.PV', 'MZLJ_KWh.PV', 'MZLJ_TemSP.PV', 'MZLJ_TemSP1.PV',
             'MZLJ_TemSP2.PV', 'MZLJ_TemSP3.PV', 'MZLJ_TemSP4.PV', 'MZLJ_TemSPEN1.PV', 'MZLJ_TemSPEN2.PV',
             'MZLJ_TemSPEN3.PV', 'MZLJ_TemSPEN4.PV', 'MZLJ1_A.PV', 'MZLJ1_Alarm.PV', 'MZLJ1_ChuShi.PV',
             'MZLJ1_Clear.PV', 'MZLJ1_KW.PV', 'MZLJ1_KWh.PV', 'MZLJ1_ManAuto.PV', 'MZLJ1_ManOn.PV', 'MZLJ1_Mode.PV',
             'MZLJ1_NeedRep.PV', 'MZLJ1_Repair.PV', 'MZLJ1_RepTime.PV', 'MZLJ1_Run.PV', 'MZLJ1_RunTime.PV',
             'MZLJ2_A.PV', 'MZLJ2_Alarm.PV', 'MZLJ2_ChuShi.PV', 'MZLJ2_Clear.PV', 'MZLJ2_KW.PV', 'MZLJ2_KWh.PV',
             'MZLJ2_ManAuto.PV', 'MZLJ2_ManOn.PV', 'MZLJ2_Mode.PV', 'MZLJ2_NeedRep.PV', 'MZLJ2_Repair.PV',
             'MZLJ2_RepTime.PV', 'MZLJ2_Run.PV', 'MZLJ2_RunTime.PV', 'MZLJ3_A.PV', 'MZLJ3_Alarm.PV', 'MZLJ3_ChuShi.PV',
             'MZLJ3_Clear.PV', 'MZLJ3_KW.PV', 'MZLJ3_KWh.PV', 'MZLJ3_ManAuto.PV', 'MZLJ3_ManOn.PV', 'MZLJ3_Mode.PV',
             'MZLJ3_NeedRep.PV', 'MZLJ3_Repair.PV', 'MZLJ3_RepTime.PV', 'MZLJ3_Run.PV', 'MZLJ3_RunTime.PV',
             'MZLJ4_A.PV', 'MZLJ4_Alarm.PV', 'MZLJ4_ChuShi.PV', 'MZLJ4_Clear.PV', 'MZLJ4_KW.PV', 'MZLJ4_KWh.PV',
             'MZLJ4_ManAuto.PV', 'MZLJ4_ManOn.PV', 'MZLJ4_Mode.PV', 'MZLJ4_NeedRep.PV', 'MZLJ4_Repair.PV',
             'MZLJ4_RepTime.PV', 'MZLJ4_Run.PV', 'MZLJ4_RunTime.PV', 'MZLJ5_A.PV', 'MZLJ5_Alarm.PV', 'MZLJ5_ChuShi.PV',
             'MZLJ5_Clear.PV', 'MZLJ5_KW.PV', 'MZLJ5_KWh.PV', 'MZLJ5_ManAuto.PV', 'MZLJ5_ManOn.PV', 'MZLJ5_Mode.PV',
             'MZLJ5_NeedRep.PV', 'MZLJ5_Repair.PV', 'MZLJ5_RepTime.PV', 'MZLJ5_Run.PV', 'MZLJ5_RunTime.PV',
             'MZLJ6_A.PV', 'MZLJ6_Alarm.PV', 'MZLJ6_ChuShi.PV', 'MZLJ6_Clear.PV', 'MZLJ6_KW.PV', 'MZLJ6_KWh.PV',
             'MZLJ6_ManAuto.PV', 'MZLJ6_ManOn.PV', 'MZLJ6_Mode.PV', 'MZLJ6_NeedRep.PV', 'MZLJ6_Repair.PV',
             'MZLJ6_RepTime.PV', 'MZLJ6_Run.PV', 'MZLJ6_RunTime.PV', 'MZQ_LJLL.PV', 'MZQ_LJRL.PV', 'MZQ_MD.PV',
             'MZQ_PL.PV', 'MZQ_RH.PV', 'MZQ_SSLL.PV', 'MZQ_SSRL.PV', 'MZQ_WD.PV', 'MZQ_YC.PV', 'MZQ_YL.PV',
             'OffHour1.PV', 'OffHour2.PV', 'OffHour3.PV', 'OffHour4.PV', 'OffHour5.PV', 'OffHour6.PV', 'OffHour7.PV',
             'OffMinute1.PV', 'OffMinute2.PV', 'OffMinute3.PV', 'OffMinute4.PV', 'OffMinute5.PV', 'OffMinute6.PV',
             'OffMinute7.PV', 'OnHour1.PV', 'OnHour2.PV', 'OnHour3.PV', 'OnHour4.PV', 'OnHour5.PV', 'OnHour6.PV',
             'OnHour7.PV', 'OnMinute1.PV', 'OnMinute2.PV', 'OnMinute3.PV', 'OnMinute4.PV', 'OnMinute5.PV',
             'OnMinute6.PV', 'OnMinute7.PV', 'OUT_Hum.PV', 'OUT_Tem.PV', 'OutTem_EN.PV', 'ParA1.PV', 'ParA10.PV',
             'ParA2.PV', 'ParA3.PV', 'ParA4.PV', 'ParA5.PV', 'ParA6.PV', 'ParA7.PV', 'ParA8.PV', 'ParA9.PV', 'ParB1.PV',
             'ParB10.PV', 'ParB2.PV', 'ParB3.PV', 'ParB4.PV', 'ParB5.PV', 'ParB6.PV', 'ParB7.PV', 'ParB8.PV',
             'ParB9.PV', 'ParC1.PV', 'ParC10.PV', 'ParC2.PV', 'ParC3.PV', 'ParC4.PV', 'ParC5.PV', 'ParC6.PV',
             'ParC7.PV', 'ParC8.PV', 'ParC9.PV', 'ParD1.PV', 'ParD10.PV', 'ParD2.PV', 'ParD3.PV', 'ParD4.PV',
             'ParD5.PV', 'ParD6.PV', 'ParD7.PV', 'ParD8.PV', 'ParD9.PV', 'ParE1.PV', 'ParE10.PV', 'ParE2.PV',
             'ParE3.PV', 'ParE4.PV', 'ParE5.PV', 'ParE6.PV', 'ParE7.PV', 'ParE8.PV', 'ParE9.PV', 'PC_Day.PV',
             'PC_Hour.PV', 'PC_Minute.PV', 'PC_Month.PV', 'PC_Year.PV', 'PHF_DB.PV', 'PHF_FB1.PV', 'PHF_FB2.PV',
             'PHF_FB3.PV', 'PHF_FB4.PV', 'PHF_HighSP.PV', 'PHF_I.PV', 'PHF_LowSP.PV', 'PHF_ManAuto1.PV',
             'PHF_ManAuto2.PV', 'PHF_ManAuto3.PV', 'PHF_ManAuto4.PV', 'PHF_OutSP1.PV', 'PHF_OutSP2.PV', 'PHF_OutSP3.PV',
             'PHF_OutSP4.PV', 'PHF_P.PV', 'RKWD.PV', 'RLLJ.PV', 'RSB_DB.PV', 'RSB_DNB1.PV', 'RSB_HighSP1.PV',
             'RSB_I.PV', 'RSB_KW.PV', 'RSB_KWh.PV', 'RSB_P.PV', 'RSB_PSet.PV', 'RSB1_A.PV', 'RSB1_Alarm.PV',
             'RSB1_Clear.PV', 'RSB1_Fre_FB.PV', 'RSB1_FreSP.PV', 'RSB1_KW.PV', 'MLQB4_RunTime.PV', 'MLQB5_A.PV',
             'MLQB5_Alarm.PV', 'MLQB5_Clear.PV', 'MLQB5_Fre_FB.PV', 'MLQB5_FreSP.PV', 'MLQB5_KW.PV', 'MLQB5_KWh.PV',
             'MLQB5_ManAuto.PV', 'MLQB5_ManOn.PV', 'MLQB5_Mode.PV', 'MLQB5_NeedRep.PV', 'MLQB5_Repair.PV',
             'MLQB5_RepTime.PV', 'MLQB5_Run.PV', 'MLQB5_RunTime.PV', 'MLQB6_A.PV', 'MLQB6_Alarm.PV', 'MLQB6_Clear.PV',
             'MLQB6_Fre_FB.PV', 'MLQB6_FreSP.PV', 'MLQB6_KW.PV', 'MLQB6_KWh.PV', 'MLQB6_ManAuto.PV', 'MLQB6_ManOn.PV',
             'MLQB6_Mode.PV', 'MLQB6_NeedRep.PV', 'MLQB6_Repair.PV', 'MLQB6_RepTime.PV', 'MLQB6_Run.PV',
             'MLQB6_RunTime.PV', 'MLQB7_A.PV', 'MLQB7_Alarm.PV', 'MLQB7_Clear.PV', 'MLQB7_Fre_FB.PV', 'MLQB7_FreSP.PV',
             'MLQB7_KW.PV', 'MLQB7_KWh.PV', 'MLQB7_ManAuto.PV', 'MLQB7_ManOn.PV', 'MLQB7_Mode.PV', 'MLQB7_NeedRep.PV',
             'MLQB7_Repair.PV', 'MLQB7_RepTime.PV', 'MLQB7_Run.PV', 'MLQB7_RunTime.PV', 'MLQB8_A.PV', 'MLQB8_Alarm.PV',
             'MLQB8_Clear.PV', 'MLQB8_Fre_FB.PV', 'MLQB8_FreSP.PV', 'MLQB8_KW.PV', 'MLQB8_KWh.PV', 'MLQB8_ManAuto.PV',
             'MLQB8_ManOn.PV', 'MLQB8_Mode.PV', 'MLQB8_NeedRep.PV', 'MLQB8_Repair.PV', 'MLQB8_RepTime.PV',
             'MLQB8_Run.PV', 'MLQB8_RunTime.PV', 'MLQF_Stop1.PV', 'MLQF_Stop2.PV', 'MLQF_Stop3.PV', 'MLQF_Stop4.PV',
             'MLQF_Stop5.PV', 'MLQF_Stop6.PV', 'MLQF1_Close.PV', 'MLQF1_FBClose.PV', 'MLQF1_FBOpen.PV',
             'MLQF1_ManAuto.PV', 'MLQF1_Open.PV', 'MLQF2_Close.PV', 'MLQF2_FBClose.PV', 'MLQF2_FBOpen.PV',
             'MLQF2_ManAuto.PV', 'MLQF2_Open.PV', 'MLQF3_Close.PV', 'MLQF3_FBClose.PV', 'MLQF3_FBOpen.PV',
             'MLQF3_ManAuto.PV', 'MLQF3_Open.PV', 'MLQF4_Close.PV', 'MLQF4_FBClose.PV', 'MLQF4_FBOpen.PV',
             'MLQF4_ManAuto.PV', 'MLQF4_Open.PV', 'MLQF5_Close.PV', 'MLQF5_FBClose.PV', 'MLQF5_FBOpen.PV',
             'MLQF5_ManAuto.PV', 'MLQF5_Open.PV', 'MLQF6_Close.PV', 'MLQF6_FBClose.PV', 'MLQF6_FBOpen.PV',
             'MLQF6_ManAuto.PV', 'MLQF6_Open.PV', 'MLQGS1_Tem.PV', 'MLQGS2_Tem.PV', 'MLQHS1_Tem.PV', 'MLQHS2_Tem.PV',
             'MLQTF1_Close.PV', 'MLQTF1_FBClose.PV', 'MLQTF1_FBOpen.PV', 'MLQTF1_ManAuto.PV', 'MLQTF1_Open.PV',
             'MLQTF10_Close.PV', 'MLQTF10_FBClose.PV', 'MLQTF10_FBOpen.PV', 'MLQTF10_ManAuto.PV', 'MLQTF10_Open.PV',
             'MLQTF11_Close.PV', 'MLQTF11_FBClose.PV', 'MLQTF11_FBOpen.PV', 'MLQTF11_ManAuto.PV', 'MLQTF11_Open.PV',
             'MLQTF12_Close.PV', 'MLQTF12_FBClose.PV', 'MLQTF12_FBOpen.PV', 'MLQTF12_ManAuto.PV', 'MLQTF12_Open.PV',
             'MLQTF13_Close.PV', 'MLQTF13_FBClose.PV', 'MLQTF13_FBOpen.PV', 'MLQTF13_ManAuto.PV', 'MLQTF13_Open.PV',
             'MLQTF14_Close.PV', 'MLQTF14_FBClose.PV', 'MLQTF14_FBOpen.PV', 'MLQTF14_ManAuto.PV', 'MLQTF14_Open.PV',
             'MLQTF15_Close.PV', 'MLQTF15_FBClose.PV', 'MLQTF15_FBOpen.PV', 'MLQTF15_ManAuto.PV', 'MLQTF15_Open.PV',
             'MLQTF16_Close.PV', 'MLQTF16_FBClose.PV', 'MLQTF16_FBOpen.PV', 'MLQTF16_ManAuto.PV', 'MLQTF16_Open.PV',
             'MLQTF2_Close.PV', 'MLQTF2_FBClose.PV', 'MLQTF2_FBOpen.PV', 'MLQTF2_ManAuto.PV', 'MLQTF2_Open.PV',
             'MLQTF3_Close.PV', 'MLQTF3_FBClose.PV', 'MLQTF3_FBOpen.PV', 'MLQTF3_ManAuto.PV', 'MLQTF3_Open.PV',
             'MLQTF4_Close.PV', 'MLQTF4_FBClose.PV', 'MLQTF4_FBOpen.PV', 'MLQTF4_ManAuto.PV', 'MLQTF4_Open.PV',
             'MLQTF5_Close.PV', 'MLQTF5_FBClose.PV', 'MLQTF5_FBOpen.PV', 'MLQTF5_ManAuto.PV', 'MLQTF5_Open.PV',
             'MLQTF6_Close.PV', 'MLQTF6_FBClose.PV', 'MLQTF6_FBOpen.PV', 'MLQTF6_ManAuto.PV', 'MLQTF6_Open.PV',
             'MLQTF7_Close.PV', 'MLQTF7_FBClose.PV', 'MLQTF7_FBOpen.PV', 'MLQTF7_ManAuto.PV', 'MLQTF7_Open.PV',
             'MLQTF8_Close.PV', 'MLQTF8_FBClose.PV', 'MLQTF8_FBOpen.PV', 'MLQTF8_ManAuto.PV', 'MLQTF8_Open.PV',
             'MLQTF9_Close.PV', 'MLQTF9_FBClose.PV', 'MLQTF9_FBOpen.PV', 'MLQTF9_ManAuto.PV', 'MLQTF9_Open.PV',
             'MMode.PV', 'MMode1_En.PV', 'MMode1_HourSP1.PV', 'MMode1_HourSP2.PV', 'MMode1_MinSP1.PV',
             'MMode1_MinSP2.PV', 'MMode2_En.PV', 'MMode2_HourSP1.PV', 'MMode2_HourSP2.PV', 'MMode2_MinSP1.PV',
             'MMode2_MinSP2.PV', 'MMode3_En.PV', 'MMode3_HourSP.PV', 'MMode3_MinSP.PV', 'MMode4_En.PV',
             'MMode4_HourSP.PV', 'MMode4_MinSP.PV', 'Mode.PV', 'Mode1_En.PV', 'Mode1_HourSP1.PV', 'Mode1_HourSP2.PV',
             'Mode1_MinSP1.PV', 'Mode1_MinSP2.PV', 'Mode2_En.PV', 'Mode2_HourSP1.PV', 'Mode2_HourSP2.PV',
             'Mode2_MinSP1.PV', 'Mode2_MinSP2.PV', 'Mode3_En.PV', 'Mode3_HourSP.PV', 'Mode3_MinSP.PV', 'Mode4_En.PV',
             'Mode4_HourSP.PV', 'Mode4_MinSP.PV', 'MOffHour1.PV', 'MOffHour2.PV', 'MOffHour3.PV', 'MOffHour4.PV',
             'MOffHour5.PV', 'MOffHour6.PV', 'MOffHour7.PV', 'MOffMinute1.PV', 'MOffMinute2.PV', 'MOffMinute3.PV',
             'MOffMinute4.PV', 'MOffMinute5.PV', 'MOffMinute6.PV', 'MOffMinute7.PV', 'MOnHour1.PV', 'MOnHour2.PV',
             'MOnHour3.PV', 'MOnHour4.PV', 'MOnHour5.PV', 'MOnHour6.PV', 'MOnHour7.PV', 'MOnMinute1.PV', '2HL_LowX8.PV',
             '2HL_LowX9.PV', '2HL_Tem_SPD1.PV', '2HL_Tem_SPD10.PV', '2HL_Tem_SPD2.PV', '2HL_Tem_SPD3.PV',
             '2HL_Tem_SPD4.PV', '2HL_Tem_SPD5.PV', '2HL_Tem_SPD6.PV', '2HL_Tem_SPD7.PV', '2HL_Tem_SPD8.PV',
             '2HL_Tem_SPD9.PV', '2HL_Tem_SPX1.PV', '2HL_Tem_SPX10.PV', '2HL_Tem_SPX2.PV', '2HL_Tem_SPX3.PV',
             '2HL_Tem_SPX4.PV', '2HL_Tem_SPX5.PV', '2HL_Tem_SPX6.PV', '2HL_Tem_SPX7.PV', '2HL_Tem_SPX8.PV',
             '2HL_Tem_SPX9.PV', '2LDB_Hz_Low.PV', '2LDGS_P_SP1.PV', '2LDGS_P_SP2.PV', '2LDGS_P_SP3.PV',
             '2LDGS_P_SP4.PV', '2LDGS_P_SP5.PV', '2LDGS_P_SP6.PV', '2LQB_Hz_Low.PV', '2RSB_Hz_Low.PV', '2RSGS_P_SP1.PV',
             '2RSGS_P_SP2.PV', '2RSGS_P_SP3.PV', '2RSGS_Tem_SP.PV', '2SUB_Cur1.PV', '2SUB_T.PV', '2ZLJ_MAX.PV',
             '2ZLJ_MIN.PV', '2ZQF_Low.PV', '3ADD_Cur1.PV', '3ADD_T.PV', '3FJSQ_P_SPD.PV', '3FJSQ_P_SPX.PV',
             '3HL_LowX1.PV', '3HL_LowX10.PV', '3HL_LowX2.PV', '3HL_LowX3.PV', '3HL_LowX4.PV', '3HL_LowX5.PV',
             '3HL_LowX6.PV', '3HL_LowX7.PV', '3HL_LowX8.PV', '3HL_LowX9.PV', '3HL_Tem_SPD1.PV', '3HL_Tem_SPD10.PV',
             '3HL_Tem_SPD2.PV', '3HL_Tem_SPD3.PV', '3HL_Tem_SPD4.PV', '3HL_Tem_SPD5.PV', '3HL_Tem_SPD6.PV',
             '3HL_Tem_SPD7.PV', '3HL_Tem_SPD8.PV', '3HL_Tem_SPD9.PV', '3HL_Tem_SPX1.PV', '3HL_Tem_SPX10.PV',
             '3HL_Tem_SPX2.PV', '3HL_Tem_SPX3.PV', '3HL_Tem_SPX4.PV', '3HL_Tem_SPX5.PV', '3HL_Tem_SPX6.PV',
             '3HL_Tem_SPX7.PV', '3HL_Tem_SPX8.PV', '3HL_Tem_SPX9.PV', '3LDB_Hz_Low.PV', '3LDGS_P_SP1.PV',
             '3LDGS_P_SP2.PV', '3LDGS_P_SP3.PV', '3LDGS_P_SP4.PV', '3LDGS_P_SP5.PV', '3LDGS_P_SP6.PV', '3LQB_Hz_Low.PV',
             '3RSB_Hz_Low.PV', '3RSGS_P_SP1.PV', '3RSGS_P_SP2.PV', '3RSGS_P_SP3.PV', '3RSGS_Tem_SP.PV', '3SUB_Cur1.PV',
             '3SUB_T.PV', '3ZLJ_MAX.PV', '3ZLJ_MIN.PV', '3ZQF_Low.PV', '4ADD_Cur1.PV', '4ADD_T.PV', '4FJSQ_P_SPD.PV',
             '4FJSQ_P_SPX.PV', '4HL_LowX1.PV', '4HL_LowX10.PV', '4HL_LowX2.PV', '4HL_LowX3.PV', '4HL_LowX4.PV',
             '4HL_LowX5.PV', '4HL_LowX6.PV', '4HL_LowX7.PV', '4HL_LowX8.PV', '4HL_LowX9.PV', '4HL_Tem_SPD1.PV',
             '4HL_Tem_SPD10.PV', '4HL_Tem_SPD2.PV', '4HL_Tem_SPD3.PV', '4HL_Tem_SPD4.PV', '4HL_Tem_SPD5.PV',
             '4HL_Tem_SPD6.PV', '4HL_Tem_SPD7.PV', '4HL_Tem_SPD8.PV', '4HL_Tem_SPD9.PV', '4HL_Tem_SPX1.PV',
             '4HL_Tem_SPX10.PV', '4HL_Tem_SPX2.PV', '4HL_Tem_SPX3.PV', '4HL_Tem_SPX4.PV', '4HL_Tem_SPX5.PV',
             '4HL_Tem_SPX6.PV', '4HL_Tem_SPX7.PV', '4HL_Tem_SPX8.PV', '4HL_Tem_SPX9.PV', '4LDB_Hz_Low.PV',
             '4LDGS_P_SP1.PV', '4LDGS_P_SP2.PV', '4LDGS_P_SP3.PV', '4LDGS_P_SP4.PV', '4LDGS_P_SP5.PV', '4LDGS_P_SP6.PV',
             '4LQB_Hz_Low.PV', '4RSB_Hz_Low.PV', '4RSGS_P_SP1.PV', '4RSGS_P_SP2.PV', '4RSGS_P_SP3.PV',
             '4RSGS_Tem_SP.PV', '4SUB_Cur1.PV', '4SUB_T.PV', '4ZLJ_MAX.PV', '4ZLJ_MIN.PV', '4ZQF_Low.PV', 'A1.PV',
             'A2.PV', 'A3.PV', 'A4.PV', 'A5.PV', 'A6.PV', 'A7.PV', 'A8.PV', 'ADD_Cur2.PV', 'Add_Pan1.PV', 'Add_Pan2.PV',
             'AddDelay.PV', 'ADDSUB_Time1.PV', 'ADDSUB_Time2.PV', 'ALA_T1.PV', 'ALA_T2.PV', 'ALA_T3.PV', 'ALA_T4.PV',
             'AutoStart.PV', 'AutoStartR.PV', 'B1.PV', 'B2.PV', 'B3.PV', 'B4.PV', 'B5.PV', 'B6.PV', 'B7.PV', 'B8.PV',
             'BAN_Auto.PV', 'BG_Time.PV', 'BPWDD.PV', 'BPWDX.PV', 'C1.PV', 'C2.PV', 'C3.PV', 'C4.PV', 'C5.PV', 'C6.PV',
             'C7.PV', 'C8.PV', 'ChuShi_EN.PV', 'CKWD.PV', 'Com_Error1.PV', 'Com_Error2.PV', 'Com_Error3.PV',
             'Com_Error4.PV', 'Com_Error5.PV', 'Com_Error6.PV', 'Com_Error7.PV', 'Com_Error8.PV', 'COP.PV',
             'CS_Delay1.PV', 'CS_Delay2.PV', 'D1.PV', 'D2.PV', 'D3.PV', 'D4.PV', 'D5.PV', 'D6.PV', 'D7.PV', 'D8.PV',
             'DDC_Day.PV', 'DDC_Hour.PV', 'DDC_Minute.PV', 'DDC_Month.PV', 'DDC_Week.PV', 'DDC_Year.PV', 'Delay1.PV',
             'Delay2.PV', 'Delay3.PV', 'Delay4.PV', 'Delay5.PV', 'Delay6.PV', 'DingShiEn.PV', 'DNB_Error1.PV',
             'DNB_Error10.PV', 'DNB_Error11.PV', 'DNB_Error12.PV', 'DNB_Error13.PV', 'DNB_Error14.PV', 'DNB_Error15.PV',
             'DNB_Error16.PV', 'DNB_Error2.PV', 'DNB_Error3.PV', 'DNB_Error4.PV', 'DNB_Error5.PV', 'DNB_Error6.PV',
             'DNB_Error7.PV', 'DNB_Error8.PV', 'DNB_Error9.PV', 'DT_H.PV', 'DT_H1.PV', 'DT_L.PV', 'DT_L1.PV', 'DT_M.PV',
             'DT_M1.PV', 'E1.PV', 'E2.PV', 'E3.PV', 'E4.PV', 'E5.PV', 'E6.PV', 'E7.PV', 'E8.PV', 'ECB_DB.PV',
             'ECB_DNB1.PV', 'ECB_HighSP1.PV', 'ECB_I.PV', 'ECB_KW.PV', 'ECB_KWh.PV', 'ECB_P.PV', 'ECB1_A.PV',
             'ECB1_Alarm.PV', 'ECB1_Clear.PV', 'ECB1_Fre_FB.PV', 'ECB1_FreSP.PV', 'ECB1_KW.PV', 'ECB1_KWh.PV',
             'ECB1_ManAuto.PV', 'ECB1_ManOn.PV', 'ECB1_Mode.PV', 'ECB1_NeedRep.PV', 'ECB1_Repair.PV', 'ECB1_RepTime.PV',
             'ECB1_Run.PV', 'ECB1_RunTime.PV', 'ECB2_A.PV', 'ECB2_Alarm.PV', 'ECB2_Clear.PV', 'ECB2_Fre_FB.PV',
             'ECB2_FreSP.PV', 'ECB2_KW.PV', 'ECB2_KWh.PV', 'ECB2_ManAuto.PV', 'ECB2_ManOn.PV', 'ECB2_Mode.PV',
             'ECB2_NeedRep.PV', 'ECB2_Repair.PV', 'ECB2_RepTime.PV', 'ECB2_Run.PV', 'ECB2_RunTime.PV', 'ECB3_A.PV',
             'ECB3_Alarm.PV', 'ECB3_Clear.PV', 'ECB3_Fre_FB.PV', 'ECB3_FreSP.PV', 'ECB3_KW.PV', 'ECB3_KWh.PV',
             'ECB3_ManAuto.PV', 'ECB3_ManOn.PV', 'ECB3_Mode.PV', 'ECB3_NeedRep.PV', 'ECB3_Repair.PV', 'ECB3_RepTime.PV',
             'ECB3_Run.PV', 'ECB3_RunTime.PV', 'ECB4_A.PV', 'ECB4_Alarm.PV', 'ECB4_Clear.PV', 'ECB4_Fre_FB.PV',
             'ECB4_FreSP.PV', 'ECB4_KW.PV', 'ECB4_KWh.PV', 'ECB4_ManAuto.PV', 'ECB4_ManOn.PV', 'ECB4_Mode.PV',
             'ECB4_NeedRep.PV', 'ECB4_Repair.PV', 'ECB4_RepTime.PV', 'ECB4_Run.PV', 'ECB4_RunTime.PV', 'ECB5_A.PV',
             'ECB5_Alarm.PV', 'ECB5_Clear.PV', 'ECB5_Fre_FB.PV', 'ECB5_FreSP.PV', 'ECB5_KW.PV', 'ECB5_KWh.PV',
             'ECB5_ManAuto.PV', 'ECB5_ManOn.PV', 'ECB5_Mode.PV', 'ECB5_NeedRep.PV', 'ECB5_Repair.PV', 'ECB5_RepTime.PV',
             'ECB5_Run.PV', 'ECB5_RunTime.PV', 'ECB6_A.PV', 'ECB6_Alarm.PV', 'ECB6_Clear.PV', 'ECB6_Fre_FB.PV',
             'ECB6_FreSP.PV', 'ECB6_KW.PV', 'ECB6_KWh.PV', 'ECB6_ManAuto.PV', 'ECB6_ManOn.PV', 'ECB6_Mode.PV',
             'ECB6_NeedRep.PV', 'ECB6_Repair.PV', 'ECB6_RepTime.PV', 'ECB6_Run.PV', 'ECB6_RunTime.PV', 'ECRB_DB.PV',
             'ECRB_DNB1.PV', 'ECRB_HighSP1.PV', 'ECRB_I.PV', 'ECRB_KW.PV', 'ECRB_KWh.PV', 'ECRB_P.PV', 'ECRB1_A.PV',
             'ECRB1_Alarm.PV', 'ECRB1_Clear.PV', 'ECRB1_Fre_FB.PV', 'ECRB1_FreSP.PV', 'ECRB1_KW.PV', 'ECRB1_KWh.PV',
             'ECRB1_ManAuto.PV', 'ECRB1_ManOn.PV', 'ECRB1_Mode.PV', 'ECRB1_NeedRep.PV', 'ECRB1_Repair.PV',
             'ECRB1_RepTime.PV', 'ECRB1_Run.PV', 'ECRB1_RunTime.PV', 'ECRB2_A.PV', 'ECRB2_Alarm.PV', 'ECRB2_Clear.PV',
             'ECRB2_Fre_FB.PV', 'ECRB2_FreSP.PV', 'ECRB2_KW.PV', 'ECRB2_KWh.PV', 'ECRB2_ManAuto.PV', 'ECRB2_ManOn.PV',
             'ECRB2_Mode.PV', 'ECRB2_NeedRep.PV', 'ECRB2_Repair.PV', 'ECRB2_RepTime.PV', 'ECRB2_Run.PV',
             'ECRB2_RunTime.PV', 'ECRB3_A.PV', 'ECRB3_Alarm.PV', 'ECRB3_Clear.PV', 'ECRB3_Fre_FB.PV', 'ECRB3_FreSP.PV',
             'ECRB3_KW.PV', 'ECRB3_KWh.PV', 'ECRB3_ManAuto.PV', 'ECRB3_ManOn.PV', 'ECRB3_Mode.PV', 'ECRB3_NeedRep.PV',
             'ECRB3_Repair.PV', 'ECRB3_RepTime.PV', 'ECRB3_Run.PV', 'ECRB3_RunTime.PV', 'ECRB4_A.PV', 'ECRB4_Alarm.PV',
             'ECRB4_Clear.PV', 'ECRB4_Fre_FB.PV', 'ECRB4_FreSP.PV', 'ECRB4_KW.PV', 'ECRB4_KWh.PV', 'ECRB4_ManAuto.PV',
             'ECRB4_ManOn.PV', 'ECRB4_Mode.PV', 'ECRB4_NeedRep.PV', 'ECRB4_Repair.PV', 'ECRB4_RepTime.PV',
             'ECRB4_Run.PV', 'ECRB4_RunTime.PV', 'ECRB5_A.PV', 'ECRB5_Alarm.PV', 'ECRB5_Clear.PV', 'ECRB5_Fre_FB.PV',
             'ECRB5_FreSP.PV', 'ECRB5_KW.PV', 'ECRB5_KWh.PV', 'ECRB5_ManAuto.PV', 'ECRB5_ManOn.PV', 'ECRB5_Mode.PV',
             'ECRB5_NeedRep.PV', 'ECRB5_Repair.PV', 'ECRB5_RepTime.PV', 'ECRB5_Run.PV', 'ECRB5_RunTime.PV',
             'ECRB6_A.PV', 'ECRB6_Alarm.PV', 'ECRB6_Clear.PV', 'ECRB6_Fre_FB.PV', 'ECRB6_FreSP.PV', 'ECRB6_KW.PV',
             'ECRB6_KWh.PV', 'ECRB6_ManAuto.PV', 'ECRB6_ManOn.PV', 'ECRB6_Mode.PV', 'ECRB6_NeedRep.PV',
             'ECRB6_Repair.PV', 'ECRB6_RepTime.PV', 'ECRB6_Run.PV', 'ECRB6_RunTime.PV', 'F1.PV', 'F2.PV', 'F3.PV',
             'F4.PV', 'F5.PV', 'F6.PV', 'F7.PV', 'F8.PV', 'FINAL1_DATA1.PV', 'FINAL1_DATA10.PV', 'FINAL1_DATA11.PV',
             'FINAL1_DATA12.PV', 'FINAL1_DATA13.PV', 'FINAL1_DATA14.PV', 'FINAL1_DATA15.PV', 'FINAL1_DATA16.PV',
             'FINAL1_DATA17.PV', 'FINAL1_DATA18.PV', 'FINAL1_DATA19.PV', 'FINAL1_DATA2.PV', 'FINAL1_DATA20.PV',
             'FINAL1_DATA21.PV', 'FINAL1_DATA22.PV', 'FINAL1_DATA23.PV', 'FINAL1_DATA24.PV', 'FINAL1_DATA25.PV',
             'FINAL1_DATA3.PV', 'FINAL1_DATA4.PV', 'FINAL1_DATA5.PV', 'FINAL1_DATA6.PV', 'FINAL1_DATA7.PV',
             'FINAL1_DATA8.PV', 'FINAL1_DATA9.PV', 'FINAL2_DATA1.PV', 'FINAL2_DATA10.PV', 'FINAL2_DATA11.PV',
             'FINAL2_DATA12.PV', 'FINAL2_DATA13.PV', 'FINAL2_DATA14.PV', 'FINAL2_DATA15.PV', 'FINAL2_DATA16.PV',
             'FINAL2_DATA17.PV', 'FINAL2_DATA18.PV', 'FINAL2_DATA19.PV', 'FINAL2_DATA2.PV', 'FINAL2_DATA20.PV',
             'FINAL2_DATA21.PV', 'FINAL2_DATA22.PV', 'FINAL2_DATA23.PV', 'FINAL2_DATA24.PV', 'FINAL2_DATA25.PV',
             'FINAL2_DATA3.PV', 'FINAL2_DATA4.PV', 'FINAL2_DATA5.PV', 'FINAL2_DATA6.PV', 'FINAL2_DATA7.PV',
             'FINAL2_DATA8.PV', 'FINAL2_DATA9.PV', 'FINAL3_DATA1.PV', 'FINAL3_DATA10.PV', 'FINAL3_DATA11.PV',
             'FINAL3_DATA12.PV', 'FINAL3_DATA13.PV', 'FINAL3_DATA14.PV', 'FINAL3_DATA15.PV', 'FINAL3_DATA16.PV',
             'FINAL3_DATA17.PV', 'FINAL3_DATA18.PV', 'FINAL3_DATA19.PV', 'FINAL3_DATA2.PV', 'FINAL3_DATA20.PV',
             'FINAL3_DATA21.PV', 'FINAL3_DATA22.PV', 'FINAL3_DATA23.PV', 'FINAL3_DATA24.PV', 'FINAL3_DATA25.PV',
             'FINAL3_DATA3.PV', 'FINAL3_DATA4.PV', 'FINAL3_DATA5.PV', 'FINAL3_DATA6.PV', 'FINAL3_DATA7.PV',
             'FINAL3_DATA8.PV', 'FINAL3_DATA9.PV', 'FJ_Burst1.PV', 'FJ_Burst2.PV', 'FJ_Burst3.PV', 'FJ_BurstTem1.PV',
             'FJ_BurstTem2.PV', 'FJ_BurstTem3.PV', 'FJ_CsNum1.PV', 'FJ_CsNum2.PV', 'FJ_CsNum3.PV', 'FJ_DB.PV',
             'FJ_DbSP1.PV', 'FJ_DbSP2.PV', 'FJ_DbSP3.PV', 'FJ_DNB1.PV', 'FJ_ERROR1.PV', 'FJ_ERROR2.PV', 'FJ_ERROR3.PV',
             'FJ_ERROR4.PV', 'FJ_ERROR5.PV', 'FJ_I.PV', 'FJ_KW.PV', 'FJ_KWh.PV', 'FJ_MAX1.PV', 'FJ_MAX2.PV',
             'FJ_MAX3.PV', 'FJ_P.PV', 'FJ_TemSP1.PV', 'FJ_TemSP2.PV', 'FJ_TemSP3.PV', 'FJ_ZhouQi1.PV', 'FJ_ZhouQi2.PV',
             'FJ_ZhouQi3.PV', 'FJ1_A.PV', 'FJ1_Alarm.PV', 'FJ1_Clear.PV', 'FJ1_Fre_FB.PV', 'FJ1_FreSP.PV', 'FJ1_KW.PV',
             'FJ1_KWh.PV', 'FJ1_ManAuto.PV', 'FJ1_ManOn.PV', 'FJ1_Mode.PV', 'FJ1_NeedRep.PV', 'FJ1_Repair.PV',
             'FJ1_RepTime.PV', 'FJ1_Run.PV', 'FJ1_RunTime.PV', 'FJ10_Alarm.PV', 'FJ10_Clear.PV', 'FJ10_Fre_FB.PV',
             'FJ10_FreSP.PV', 'FJ10_ManAuto.PV', 'FJ10_ManOn.PV', 'FJ10_Mode.PV', 'FJ10_NeedRep.PV', 'FJ10_Repair.PV',
             'FJ10_RepTime.PV', 'FJ10_Run.PV', 'FJ10_RunTime.PV', 'FJ11_Alarm.PV', 'FJ11_Clear.PV', 'FJ11_Fre_FB.PV',
             'FJ11_FreSP.PV', 'FJ11_ManAuto.PV', 'FJ11_ManOn.PV', 'FJ11_Mode.PV', 'FJ11_NeedRep.PV', 'FJ11_Repair.PV',
             'FJ11_RepTime.PV', 'FJ11_Run.PV', 'FJ11_RunTime.PV', 'FJ12_Alarm.PV', 'FJ12_Clear.PV', 'FJ12_Fre_FB.PV',
             'FJ12_FreSP.PV', 'FJ12_ManAuto.PV', 'FJ12_ManOn.PV', 'FJ12_Mode.PV', 'FJ12_NeedRep.PV', 'FJ12_Repair.PV',
             'FJ12_RepTime.PV', 'FJ12_Run.PV', 'FJ12_RunTime.PV', 'FJ13_Alarm.PV', 'FJ13_Clear.PV', 'FJ13_Fre_FB.PV',
             'FJ13_FreSP.PV', 'FJ13_ManAuto.PV', 'FJ13_ManOn.PV', 'FJ13_Mode.PV', 'FJ13_NeedRep.PV', 'FJ13_Repair.PV',
             'FJ13_RepTime.PV', 'FJ13_Run.PV', 'FJ13_RunTime.PV', 'FJ14_Alarm.PV', 'FJ14_Clear.PV', 'FJ14_Fre_FB.PV',
             'FJ14_FreSP.PV', 'FJ14_ManAuto.PV', 'FJ14_ManOn.PV', 'FJ14_Mode.PV', 'FJ14_NeedRep.PV', 'FJ14_Repair.PV',
             'FJ14_RepTime.PV', 'FJ14_Run.PV', 'FJ14_RunTime.PV', 'FJ15_Alarm.PV', 'FJ15_Clear.PV', 'FJ15_Fre_FB.PV',
             'FJ15_FreSP.PV', 'FJ15_ManAuto.PV', 'FJ15_ManOn.PV', 'FJ15_Mode.PV', 'FJ15_NeedRep.PV', 'FJ15_Repair.PV',
             'FJ15_RepTime.PV', 'FJ15_Run.PV', 'FJ15_RunTime.PV', 'FJ16_Alarm.PV', 'FJ16_Clear.PV', 'FJ16_Fre_FB.PV',
             'FJ16_FreSP.PV', 'FJ16_ManAuto.PV', 'FJ16_ManOn.PV', 'FJ16_Mode.PV', 'FJ16_NeedRep.PV', 'FJ16_Repair.PV',
             'FJ16_RepTime.PV', 'FJ16_Run.PV', 'FJ16_RunTime.PV', 'FJ2_A.PV', 'FJ2_Alarm.PV', 'FJ2_Clear.PV',
             'FJ2_Fre_FB.PV', 'FJ2_FreSP.PV', 'FJ2_KW.PV', 'FJ2_KWh.PV', 'FJ2_ManAuto.PV', 'FJ2_ManOn.PV',
             'FJ2_Mode.PV', 'FJ2_NeedRep.PV', 'FJ2_Repair.PV', 'FJ2_RepTime.PV', 'FJ2_Run.PV', 'FJ2_RunTime.PV',
             'FJ3_A.PV', 'FJ3_Alarm.PV', 'FJ3_Clear.PV', 'FJ3_Fre_FB.PV', 'FJ3_FreSP.PV', 'FJ3_KW.PV', 'FJ3_KWh.PV',
             'FJ3_ManAuto.PV', 'FJ3_ManOn.PV', 'FJ3_Mode.PV', 'FJ3_NeedRep.PV', 'FJ3_Repair.PV', 'FJ3_RepTime.PV',
             'FJ3_Run.PV', 'FJ3_RunTime.PV', 'FJ4_A.PV', 'FJ4_Alarm.PV', 'FJ4_Clear.PV', 'FJ4_Fre_FB.PV',
             'FJ4_FreSP.PV', 'FJ4_KW.PV', 'FJ4_KWh.PV', 'FJ4_ManAuto.PV', 'FJ4_ManOn.PV', 'FJ4_Mode.PV',
             'FJ4_NeedRep.PV', 'FJ4_Repair.PV', 'FJ4_RepTime.PV', 'FJ4_Run.PV', 'FJ4_RunTime.PV', 'FJ5_A.PV',
             'FJ5_Alarm.PV', 'FJ5_Clear.PV', 'FJ5_Fre_FB.PV', 'FJ5_FreSP.PV', 'FJ5_KW.PV', 'FJ5_KWh.PV',
             'FJ5_ManAuto.PV', 'FJ5_ManOn.PV', 'FJ5_Mode.PV', 'FJ5_NeedRep.PV', 'FJ5_Repair.PV', 'FJ5_RepTime.PV',
             'FJ5_Run.PV']
    listStatus = []
    opcList = opc.read(lista)  # 读取整个流程参数 0停止和手动  1启动和自动
    for line in opcList:
        collection = {}
        collection[line[0]] = line[1]
        listStatus.append(collection)
    return jsonify(listStatus)  # f返回状态结果集


if __name__ == "__main__":
    app.run(host='127.0.0.1', port=5050, debug=True)
